### ISSUE TITLE
Virtually all IT Tests require delete_repo permission on github access token but README.md is missing that

### ISSUE THREAD

**Issue by nhekfqn** [jcabi/jcabi-github#1003]
Would be nice if README.md in section about IT Tests stated that github access token has to have delete_repo permission. This permission is not set to new tokens my default. Most IT tests remove repo either in finally blocks or tearDown methods and fail if access token does not have the permission.

**Comment by yegor256** [comment]
@nhekfqn thanks, I fixed the doc

**Comment by nhekfqn** [comment]
@yegor256 I've reported a valid issue, shouldn't I get paid?

**Comment by yegor256** [comment]
@nhekfqn yes, it's a valid issue, but too small for a bug, see http://www.teamed.io/policy.html#13
