### ISSUE TITLE
RtForkTest.java:56-58: Apply this rule to other...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-github#1017]
Puzzle `989-33d6f233` in `src/test/java/com/jcabi/github/RtForkTest.java:56-58` has to be resolved: Apply this rule to other classes that use MkGrizzlyContainer and make MkGrizzlyContainers use port() given by this resource to avoid tests fail with BindException.... The puzzle was created by cyberone on 29-Jan-2015.

If you have any technical questions, don't ask me, submit new tickets instead

<hr id='w'>

**Comment by dmarkov** [comment]
@nhekfqn the issue is yours, please help

**Comment by dmarkov** [comment]
@yamstranger please go ahead with this task, it's yours

**Comment by YamStranger** [comment]
@dmarkov assign to someone else. Sorry.  It seems I was in @away mode when this task was assigned. @yegor256 can you check it please? Thanks.

**Comment by dmarkov** [comment]
> @dmarkov assign to someone else. Sorry.  It seems I was in @away mode when this task was assigned. @yegor256 can you check it please? Thanks.

@yamstranger -30 points to your rating

**Comment by dmarkov** [comment]
> @dmarkov assign to someone else. Sorry.  It seems I was in @away mode when this task was assigned. @yegor256 can you check it please? Thanks.

@yamstranger right, I'll try to find someone else for this task

**Comment by dmarkov** [comment]
@tmjee please go ahead, it's your task now, keep [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions you may have

The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by tmjee** [comment]
@dmarkov  fixed in #1166

**Comment by dmarkov** [comment]
> @dmarkov  fixed in #1166

@tmjee thanks, we will review it

**Comment by dmarkov** [comment]
@tmjee you're holding this task for 15 days already; as a reminder, don't forget to remove the `@todo` puzzle from the source code; -30 added to your rating, at the moment it is: [+45](http://www.netbout.com/b/35603?open=rating)

**Comment by tmjee** [comment]
@dmarkov this issue is pending #1162

**Comment by tmjee** [comment]
@dmarkov Commit is block by ##1180
@dmarkov Please do not assign any more issues to me. Thanks

**Comment by dmarkov** [comment]
> @dmarkov Commit is block by ##1180
> @dmarkov Please do not assign any more issues to me. Thanks

@tmjee yep, got it, let's wait for #1180 being solved

**Comment by dmarkov** [comment]
@yegor256 we waited for #1180, it is closed already

**Comment by dmarkov** [comment]
@piddubnyi this ticket is yours now, please proceed, and keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions you should ask right here... Total fixed cost of this task is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more info)

**Comment by piddubnyi** [comment]
@yegor256 #1196 is merged, please close the issue.

**Comment by yegor256** [comment]
@piddubnyi I didn't open it :) can't close. it will be closed right after the next deployment cycle

**Comment by dmarkov** [comment]
@yegor256 the code made here contains a puzzle `1017-59643c80`/#1197, which will be resolved soon

**Comment by dmarkov** [comment]
@yegor256 Finished, thanks, closing..

**Comment by dmarkov** [comment]
@piddubnyi **30 mins** sent to your balance (ID `75191065`), many thanks! It took 336 hours and 15 mins.

+30 added to your rating, at the moment it is: [+45](http://www.netbout.com/b/35966?open=rating)

**Comment by 0pdd** [comment]
@dmarkov the only puzzle [#1320](https://github.com/jcabi/jcabi-github/issues/1320) is solved here.
