### ISSUE TITLE
Missing issue event types

### ISSUE THREAD

**Issue by cvrebert** [jcabi/jcabi-github#1024]
The list of issue event type constants on http://github.jcabi.com/apidocs-0.21.3/com/jcabi/github/Event.html#field_summary seems to be missing several entries when compared against [the GitHub API docs](https://developer.github.com/v3/issues/events/#events-1), specifically:
* unassigned
* labeled
* unlabeled
* milestoned
* demilestoned
* renamed
* locked
* unlocked

I believe constants for these should be added.

**Comment by yegor256** [comment]
@rultor release, tag is `0.21.4`

**Comment by dmarkov** [comment]
@rultor please don't close it.. @cvrebert could you please close it, if it is done?
