### ISSUE TITLE
Missing Search.Qualifier value: "team"

### ISSUE THREAD

**Issue by cvrebert** [jcabi/jcabi-github#1025]
Per [the relevant GitHub API docs](https://developer.github.com/v3/search/#search-issues), GitHub supports a `team` qualifier for issue searches. The `com.jcabi.github.Search.Qualifier` enum seems to be missing a corresponding `TEAM` value.

**Comment by cvrebert** [comment]
@dmarkov No need to reopen this.

**Comment by dmarkov** [comment]
@rultor please don't close it.. @cvrebert could you please close it, if it is done?
