### ISSUE TITLE
"List issues for a repository" API missing?

### ISSUE THREAD

**Issue by cvrebert** [jcabi/jcabi-github#1027]
Am I correct that jcabi-github doesn't currently implement a wrapper for https://developer.github.com/v3/issues/#list-issues-for-a-repository ? Would be great if it did.

**Comment by rabeabdu** [comment]
Yes I confirm that too. there is no way to get all the issues open/close ones

**Comment by rabeabdu** [comment]
When will we have the we have the new release with the fixing issue

**Comment by darkled** [comment]
@cvrebert it seems you were too hurrying. This issue is not yet considered to be either bug or enhancement, no developer is assigned to it and usually issues should be fixed by another person (take a look at our [Principles of Bug Tracking](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html))

**Comment by darkled** [comment]
@yegor256 do we recognize this issue as a bug/enhancement? If yes, can we assign @cvrebert to this issue?

**Comment by rabeabdu** [comment]
Yes I recognize this issue as a enhancement?

**Comment by yegor256** [comment]
yes, looks like a bug to me, we'll fix it

**Comment by yegor256** [comment]
let me know when #1030 is merged and I'll release a new version of the library to Maven Central

**Comment by dmarkov** [comment]
we will find someone to do this task, soon

**Comment by darkled** [comment]
@dmarkov assign @cvrebert to this task please

**Comment by dmarkov** [comment]
@rultor please don't close the issue, ask @cvrebert to do this instead, since he is the author of it
