### ISSUE TITLE
Do we support java1.6?

### ISSUE THREAD

**Issue by longtimeago** [jcabi/jcabi-github#1052]
Do we support java1.6?
If yes, than we need to fix the project as if fails with java6
https://travis-ci.org/jcabi/jcabi-github/jobs/58222222

If not, than let's just exclude java6 build from travis and add update README with java requirements (now there is no information about required java there)

**Comment by cvrebert** [comment]
:+1:
It's annoying to have to check whether the Travis build failure is related or not every single time.

**Comment by dmarkov** [comment]
@rultor only @longtimeago can close this issue, since he opened it

**Comment by cvrebert** [comment]
@longtimeago Can you please close this since #1080 has been merged?

**Comment by longtimeago** [comment]
Yep, thanks
