### ISSUE TITLE
MkIssue.events() doesn't track reopenings or previous closures

### ISSUE THREAD

**Issue by cvrebert** [jcabi/jcabi-github#1055]
If you create and then `close()` and then `open()` an `MkIssue`, `MkIssue.events()` doesn't include a `reopened` event.
And if you then re-`close()` that same `MkIssue`, `MkIssue.events()` only includes the latest `closed` event, and not the earlier `closed` event.

**Comment by dmarkov** [comment]
@rultor please don't close it.. @cvrebert could you please close it, if it is done?
