### ISSUE TITLE
MkIssueLabels adds/removes don't generate Events

### ISSUE THREAD

**Issue by cvrebert** [jcabi/jcabi-github#1056]
When adding and removing labels from an `MkIssue`, unlike in the real GitHub, no `labeled` or `unlabeled` `Event`s show up in the `MkIssue.events()` stream.

**Comment by cvrebert** [comment]
(Ditto for renaming, assigning, and milestoning, but I'll wait a bit to open separate issues for those.

**Comment by dmarkov** [comment]
@rultor only @cvrebert can close this issue, since he opened it
