### ISSUE TITLE
Pull.merge(String) should not be void

### ISSUE THREAD

**Issue by sonOfRa** [jcabi/jcabi-github#1060]
As discussed in #1053 with @longtimeago, it might make sense to change the return type of the merge method in a future release, in order to allow more detailed information on a merge, even if no SHA is supplied. Doing this might break backwards compatibility, so it shouldn't be probably shouldn't be rushed into a minor release.

**Comment by dmarkov** [comment]
@yegor256 please pay attention to this issue
