### ISSUE TITLE
Issue.Smart is missing milestone() method

### ISSUE THREAD

**Issue by cvrebert** [jcabi/jcabi-github#1065]
Just like it has an `assignee` method to get the assigned user, it should have a `milestone` method to get the assigned milestone.

**Comment by dmarkov** [comment]
@yegor256 dispatch this issue please

**Comment by g4s8** [comment]
@yegor256 please, look at this issue. I need it for https://github.com/zerocracy/farm/issues/575

**Comment by yegor256** [comment]
@0crat assign @g4s8

**Comment by 0crat** [comment]
> @0crat assign @g4s8  ([here](https://github.com/jcabi/jcabi-github/issues/1065#issuecomment-370389735))

@yegor256 Thanks for your contribution, @cvrebert[/z](https://www.0crat.com/u/cvrebert)! If you would be a member of [the project](https://www.0crat.com/p/C3RUBL5H9), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by 0crat** [comment]
> @0crat assign @g4s8  ([here](https://github.com/jcabi/jcabi-github/issues/1065#issuecomment-370389735))

@yegor256 The job [#1065](https://github.com/jcabi/jcabi-github/issues/1065) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3RUBL5H9/641123212). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html). @g4s8[/z](https://www.0crat.com/u/g4s8) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains

**Comment by yegor256** [comment]
@g4s8 will you do that for free (this project is not funded) or I should re-assign?

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by g4s8** [comment]
@yegor256 yes, I'll fix it

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@0crat waiting PR review #1353

**Comment by 0crat** [comment]
> @0crat waiting PR review #1353  ([here](https://github.com/jcabi/jcabi-github/issues/1065#issuecomment-372044720))

@g4s8 The impediment for [#1065](https://github.com/jcabi/jcabi-github/issues/1065) was registered successfully by @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@cvrebert it was implemented in #1353 PR, can we close then?
