### ISSUE TITLE
Add ability to get Label that was added/removed by an Event

### ISSUE THREAD

**Issue by cvrebert** [jcabi/jcabi-github#1078]
The underlying GitHub event JSON for `labeled`/`unlabeled` events includes the Label that was added to or removed from the issue by the event (see the `label` attribute documented on https://developer.github.com/v3/issues/events/ ), but jcabi-github doesn't currently expose a way to retrieve this without accessing the raw JsonObject directly. I suggest that it should add a method for this.

**Comment by dmarkov** [comment]
@rultor don't close it, ask @cvrebert to do do it, since he created it, thanks!
