### ISSUE TITLE
CommitsComparison.smart.files() should return collection of structured objects

### ISSUE THREAD

**Issue by cvrebert** [jcabi/jcabi-github#1082]
Right now, it just returns a raw `JsonArray`. This is not typesafe and is inconvenient to work with.
(Probably needs a class like egit-github's `CommitFile`)

**Comment by dmarkov** [comment]
@cvrebert this task will get someone's attention soon

**Comment by cvrebert** [comment]
@dmarkov Please roughly define "soon". Days? Weeks? Months?

**Comment by dmarkov** [comment]
@rultor rultor closed it (automatically), @cvrebert please take a look
