### ISSUE TITLE
"List branches" API is missing

### ISSUE THREAD

**Issue by cvrebert** [jcabi/jcabi-github#1084]
jcabi-github currently seems to lack a way to access GitHub's "list repository's branches" API: https://developer.github.com/v3/repos/#list-branches

**Comment by dmarkov** [comment]
@rultor rultor closed it by mistake, @cvrebert please take a look

**Comment by cvrebert** [comment]
@dmarkov No, it closed it correctly. Reopening an issue closed via the issue creator's own pull request is stupid, imho.
