### ISSUE TITLE
"Get branch (by name)" API is missing

### ISSUE THREAD

**Issue by cvrebert** [jcabi/jcabi-github#1086]
jcabi-github currently seems to lack a way to access GitHub's "get repository branch (by name)" API:
https://developer.github.com/v3/repos/#get-branch

**Comment by dmarkov** [comment]
@yegor256 dispatch this issue please

**Comment by 0crat** [comment]
Job [#1086](https://github.com/jcabi/jcabi-github/issues/1086) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Thanks for your contribution, @cvrebert[/z](https://www.0crat.com/u/cvrebert)! If you would be a member of [the project](https://www.0crat.com/p/C9R53K5JA), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by 0pdd** [comment]
@cvrebert the puzzle [#1457](https://github.com/jcabi/jcabi-github/issues/1457) is still not solved.

**Comment by 0pdd** [comment]
@cvrebert the only puzzle [#1457](https://github.com/jcabi/jcabi-github/issues/1457) is solved here.
