### ISSUE TITLE
Unable to get head or base commits of a pull request

### ISSUE THREAD

**Issue by cvrebert** [jcabi/jcabi-github#1090]
Neither `Pull` nor `Pull.Smart` expose methods to access the `head` or `base` members of a pull request's JSON (see https://developer.github.com/v3/pulls/#get-a-single-pull-request ), so it doesn't seem easily possible to access this important pull request info via jcabi-github.
I therefore suggest that `head()` and `base()` methods be added to `Pull.Smart`.

**Comment by dmarkov** [comment]
@yegor256 please do something about this issue

**Comment by cvrebert** [comment]
#1125 will fix this.

**Comment by dmarkov** [comment]
@rultor rultor closed it by mistake, @cvrebert please take a look
