### ISSUE TITLE
"Is user X a public member of organization Y?" API is missing

### ISSUE THREAD

**Issue by cvrebert** [jcabi/jcabi-github#1091]
GitHub offers an API to check whether a given user is a public member of a given organization (https://developer.github.com/v3/orgs/members/#check-public-membership), but jcabi-github doesn't seems to expose this API. This API is very useful for making authorization decisions based on a user's organization membership.

**Comment by dmarkov** [comment]
@rultor @cvrebert please take a look, rultor closed it automatically
