### ISSUE TITLE
Repos.create() shouldn't require usage of raw JSON

### ISSUE THREAD

**Issue by cvrebert** [jcabi/jcabi-github#1094]
`Repos.create()` currently accepts a raw `JsonObject` as its argument. This is annoying to work with and not very typesafe. It would be better if it accepted a structured, well-typed object instead.

**Comment by dmarkov** [comment]
@rultor rultor closed it by mistake, @cvrebert please take a look

**Comment by cvrebert** [comment]
Again, not a mistake.
