### ISSUE TITLE
Temporary Repo creation code in tests is repetitive/verbose

### ISSUE THREAD

**Issue by cvrebert** [jcabi/jcabi-github#1096]
As a follow-up to #1095: Temporary repo creation in testcases is currently unnecessarily repetitive and verbose. There should be utility methods for the very common cases of an MkRepo named "test" and for RtRepo-s with randomly-generated names. This would allow for the avoidance of a lot of duplicate code related to test repo creation.

**Comment by dmarkov** [comment]
@rultor rultor closed it by mistake, @cvrebert please take a look

**Comment by cvrebert** [comment]
@yegor256 What project management bot is @dmarkov running? I wish to file a bug against it.

**Comment by yegor256** [comment]
@cvrebert you can email me if you any ideas: yegor@teamed.io

**Comment by cvrebert** [comment]
Thanks, will do.
