### ISSUE TITLE
Avoid using java.net.URL

### ISSUE THREAD

**Issue by cvrebert** [jcabi/jcabi-github#1099]
[`java.net.URL`'s `equals()` & `hashCode()` methods aren't implemented sanely](http://michaelscharf.blogspot.com/2006/11/javaneturlequals-and-hashcode-make.html) (see also http://findbugs.sourceforge.net/bugDescriptions.html#DMI_BLOCKING_METHODS_ON_URL), so the use of this class should be avoided. However, it's currently returned from many jcabi-github methods. These should probably return `java.net.URI`s instead.

**Comment by dmarkov** [comment]
@yegor256 dispatch this issue please

**Comment by amihaiemil** [comment]
@cvrebert The blog post is from 2006 and the findbugs page from when? Honestly, I tend to trust that any issue with such a used class has been solved in the JDK since :)

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
