### ISSUE TITLE
RtHooksITCase is now failing since geocommit has gone offline

### ISSUE THREAD

**Issue by cvrebert** [jcabi/jcabi-github#1104]
`geocommit` has gone offline and been removed from GitHub's list of services: https://github.com/github/github-services/pull/1052/files#diff-a239e193db531f93c7c3ad725aff5195
This is causing `RtHooksITCase` to fail since the test hooks it creates were for `geocommit`: https://github.com/jcabi/jcabi-github/pull/1100#issuecomment-108114012
Probably it should just use a `web` hook instead.
API docs: https://developer.github.com/v3/repos/hooks/#create-a-hook

**Comment by longtimeago** [comment]
@yegor256 please, ask alex to dispatch the issue

**Comment by dmarkov** [comment]
@rultor rultor closed it by mistake, @cvrebert please take a look
