### ISSUE TITLE
Organizations conflates User's orgs with all orgs

### ISSUE THREAD

**Issue by cvrebert** [jcabi/jcabi-github#1109]
Currently, it seems like the only way to get an `Organization` is to go through a `User`, regardless of whether that user is a member of that organization or not: `someUser.organizations().get("some-org-name")`

This is unnecessarily inconvenient and doesn't make sense logically. I therefore suggest:
* Moving `Organizations.get()`, either to `Github` (as something like `Github.organization(String name)`) or to a new non-user-related `Organizations` class
  * If the latter:
    * Renaming the current `Organizations` class to clarify that it represents only the organizations that a user is a member of
    * Adding `Github.organizations()` to return the new `Organizations` class

**Comment by dmarkov** [comment]
@rultor rultor closed it by mistake, @cvrebert please take a look

**Comment by cvrebert** [comment]
Not a mistake. @rultor is never wrong :-P
