### ISSUE TITLE
Unit tests should stop MkGrizzlyContainer in finally block

### ISSUE THREAD

**Issue by longtimeago** [jcabi/jcabi-github#1110]
There are number of tests in repo, which are using MkGrizzlyContainer.
Some of them are calling container in `try` block and stop the container in finally `block`
(such as `RtCollaboratorsTest.userCanBeAddedAsCollaborator()` )
But some of them just stop the container without any try/finally (such as `RtCollaboratorsTest.canIterate` ). This may lead to resource leaking if some exception is thrown in the middle of the test.

Let's fix them all.

**Comment by dmarkov** [comment]
@yegor256 please pay attention to this issue

**Comment by dmarkov** [comment]
@longtimeago thanks a lot for reporting, **15 mins** added to your acc, pmt ID `59894906`

**Comment by 0crat** [comment]
Job [#1110](https://github.com/jcabi/jcabi-github/issues/1110) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Thanks for your contribution, @longtimeago[/z](https://www.0crat.com/u/longtimeago)! If you would be a member of [the project](https://www.0crat.com/p/C9R53K5JA), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by 0crat** [comment]
The job [#1110](https://github.com/jcabi/jcabi-github/issues/1110) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C9R53K5JA/8ccfb5f3-2316-401b-b94f-652a1c4e42ea); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
@longtimeago the puzzle [#1461](https://github.com/jcabi/jcabi-github/issues/1461) is still not solved.

**Comment by paulodamaso** [comment]
@longtimeago Please close this one, the PR have already been merged

**Comment by 0crat** [comment]
The job [#1110](https://github.com/jcabi/jcabi-github/issues/1110) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0pdd** [comment]
@longtimeago the puzzle [#1473](https://github.com/jcabi/jcabi-github/issues/1473) is still not solved; solved: [#1461](https://github.com/jcabi/jcabi-github/issues/1461).

**Comment by 0pdd** [comment]
@longtimeago the puzzle [#1482](https://github.com/jcabi/jcabi-github/issues/1482) is still not solved; solved: [#1461](https://github.com/jcabi/jcabi-github/issues/1461), [#1473](https://github.com/jcabi/jcabi-github/issues/1473).

**Comment by 0pdd** [comment]
@longtimeago the puzzle [#1487](https://github.com/jcabi/jcabi-github/issues/1487) is still not solved; solved: [#1461](https://github.com/jcabi/jcabi-github/issues/1461), [#1473](https://github.com/jcabi/jcabi-github/issues/1473), [#1482](https://github.com/jcabi/jcabi-github/issues/1482).

**Comment by 0pdd** [comment]
@longtimeago the puzzle [#1490](https://github.com/jcabi/jcabi-github/issues/1490) is still not solved; solved: [#1461](https://github.com/jcabi/jcabi-github/issues/1461), [#1473](https://github.com/jcabi/jcabi-github/issues/1473), [#1482](https://github.com/jcabi/jcabi-github/issues/1482), [#1487](https://github.com/jcabi/jcabi-github/issues/1487).

**Comment by 0pdd** [comment]
@longtimeago the puzzle [#1492](https://github.com/jcabi/jcabi-github/issues/1492) is still not solved; solved: [#1461](https://github.com/jcabi/jcabi-github/issues/1461), [#1473](https://github.com/jcabi/jcabi-github/issues/1473), [#1482](https://github.com/jcabi/jcabi-github/issues/1482), [#1487](https://github.com/jcabi/jcabi-github/issues/1487), [#1490](https://github.com/jcabi/jcabi-github/issues/1490).
