### ISSUE TITLE
MkGrizzlyContainer is never .stop()ed in some tests

### ISSUE THREAD

**Issue by cvrebert** [jcabi/jcabi-github#1116]
After auditing the test logs' `started on port #XXX` and `stopped on port #XXX` messages, I found some tests that use `MkGrizzlyContainer` but never call `.stop()` anywhere, thus leaking open ports.
`.stop()` calls need to be added to these tests.

**Comment by dmarkov** [comment]
@rultor rultor closed it (automatically), @cvrebert please take a look
