### ISSUE TITLE
RtStatuses.java:120-120: Implement this method which gets...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-github#1130]
Puzzle `1126-bb836510` in `src/main/java/com/jcabi/github/RtStatuses.java:120-120` has to be resolved: Implement this method which gets all status messages for a given commit.... The puzzle was created by Chris Rebert on 15-Jun-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by dmarkov** [comment]
@yegor256 there is a puzzle in this code `1130-addbfb1d`/#1139, we'll resolve it later

**Comment by dmarkov** [comment]
@yegor256 The issue is closed

**Comment by 0pdd** [comment]
@dmarkov the puzzle [#unknown]() is still not solved.

**Comment by 0pdd** [comment]
@dmarkov the puzzle [#1783](https://github.com/jcabi/jcabi-github/issues/1783) is still not solved.
