### ISSUE TITLE
How to get all repos from a user?

### ISSUE THREAD

**Issue by cougil** [jcabi/jcabi-github#1144]
Hi!
I'm trying to use your API and it seems really great. 
I think it is a simple question, really simple but I don't know how to make it work.
I'd like to get all the repositories that any user has, but using the Search API I'm not able to get all their repositories, it seems that it is only returning the owned repositories by the user:

```
Iterable<Repo> gitHubRepositories = search.repos("user:" + user, "repositories", "desc");
```

What can I do in order to get all the repositories from a single user?
I think it will work asking for a request like this:

```
"https://api.github.com/users/"+user+"/repos?"+&per_page=100";
```

Best,

**Comment by dmarkov** [comment]
@yegor256 dispatch this issue please

**Comment by yegor256** [comment]
@cougil try this:

```
github.repos().iterate("");
```

**Comment by cougil** [comment]
Oh! It seems that I don't have this method :-/
I suppose is because I don't have the latest version (I have 0.9) cause I'm using maven in order to download all the dependencies. Is there any possibility to add any repository to maven in order to obtain any version of your API?
Best,

**Comment by dieffrei** [comment]
Its seems doesnt work yeat.

**Comment by amihaiemil** [comment]
Latest version as of March 2018 is ``0.36.1``: https://mvnrepository.com/artifact/com.jcabi/jcabi-github/0.36.1

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
