### ISSUE TITLE
How to search all repos based on a keyword?

### ISSUE THREAD

**Issue by KPRATIK** [jcabi/jcabi-github#1149]
I am trying to do something like this: 
https://api.github.com/search/repositories?q=tetris

Could you please help me in doing this?

THanks,
Pratik

**Comment by dmarkov** [comment]
@yegor256 please do something about this issue

**Comment by yegor256** [comment]
@KPRATIK this should work:

```java
github.search().repos("tetris", "starts", Order.ASC)
```

More information here: https://developer.github.com/v3/search/

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
