### ISSUE TITLE
How to verify login credentials?

### ISSUE THREAD

**Issue by themistoklik** [jcabi/jcabi-github#1150]
Hello,

I'm trying to find a way to verify if this:

Github github = new RtGithub("username","password");

gives a correct login attempt or not. For example if I do it with bad credentials how will I know that the login attempt has failed?

thank you

**Comment by dmarkov** [comment]
@yegor256 please do something about this issue

**Comment by yegor256** [comment]
@themistoklik just try this:

```
github.users().self().login();
```

If your credentials are valid, you will get the login of the authenticated user. If not, you will have `AssertionError`

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
