### ISSUE TITLE
Limit.Smart.reset is wrong

### ISSUE THREAD

**Issue by cvrebert** [jcabi/jcabi-github#1152]
The GitHub API uses seconds as the unit, but the `java.util.Date` constructor (which `Limit.Smart.reset()` calls) uses milliseconds instead, resulting in an incorrect conversion.

**Comment by dmarkov** [comment]
@yegor256 dispatch this issue please

**Comment by cezarykluczynski** [comment]
#1153 Fixes this.

**Comment by cvrebert** [comment]
Closing since #1153 has been merged.
