### ISSUE TITLE
Please add an example of how to use assertHeader() with the Matcher

### ISSUE THREAD

**Issue by alxn** [jcabi/jcabi-github#1156]
It would be great to see an example of [`.assertHeader(String, Matcher<Iterable<String>>)`](http://http.jcabi.com/apidocs-1.8.2/com/jcabi/http/response/RestResponse.html#assertHeader(java.lang.String, org.hamcrest.Matcher)).

**Comment by dmarkov** [comment]
@yegor256 please pay attention to this issue

**Comment by yegor256** [comment]
@alxn I think you meant to submit this ticket to jcabi-http project, right? If so, please close it here and re-submit

**Comment by alxn** [comment]
@yegor256 yes! (wth happend here! lol).
