### ISSUE TITLE
Using new Travis container-based infrastructure

### ISSUE THREAD

**Issue by pecko** [jcabi/jcabi-github#1164]
I suppose that this project can use this infrastructure (http://docs.travis-ci.com/user/workers/container-based-infrastructure/). The build starts faster, takes lower and there is bigger memory/disk limit.
Solution is trivial.

**Comment by dmarkov** [comment]
@yegor256 dispatch this issue please

**Comment by yegor256** [comment]
@pecko fixed in dad90e7 thanks
