### ISSUE TITLE
Getting a clone URL for a given repository?

### ISSUE THREAD

**Issue by io7m** [jcabi/jcabi-github#1189]
Hello.

If I have a value of type `Repo`, how do I retrieve the `clone_url` from that value? There doesn't appear to be anything in the API to do it.

**Comment by dmarkov** [comment]
@yegor256 take a look at this issue please and dispatch it somehow, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@io7m try this:

```
repo.json().getString("clone_url");
```
