### ISSUE TITLE
Latest version of jcabi-github library

### ISSUE THREAD

**Issue by arjunvijayvargiya** [jcabi/jcabi-github#1193]
what is the latest version of jcabi-github library?

**Comment by dmarkov** [comment]
@yegor256 please take a look at it and dispatch (see [par.21](http://at.teamed.io/policy.html#21))

**Comment by yegor256** [comment]
@arjunvijayvargiya it's 0.25 at the moment, see https://github.com/jcabi/jcabi-github/releases
