### ISSUE TITLE
get rid of validation api

### ISSUE THREAD

**Issue by yegor256** [jcabi/jcabi-github#1195]
Let's get rid of validation API and set its dependency `<scope>` to `test` in `pom.xml`. See how it was done here, for example: https://github.com/jcabi/jcabi-http/commit/9bf202f1d8da7d8660141ee6ea155bb4bc2cac1b

**Comment by dmarkov** [comment]
@yegor256 tag "bug" added

**Comment by dmarkov** [comment]
@yegor256 thanks for reporting! I topped your account for 15 mins, transaction 000-dfe26c22

**Comment by dmarkov** [comment]
@amihaiemil this is your task now, please help. The budget of it is **30 mins**

**Comment by amihaiemil** [comment]
@dmarkov The PR for this was reviewed and is waiting for Yegor's approval.

**Comment by dmarkov** [comment]
> @dmarkov The PR for this was reviewed and is waiting for Yegor's approval.

@amihaiemil OK

**Comment by amihaiemil** [comment]
@dmarkov The PR for this has been approved and merged today. Now it has to be deployed, I think, before closure. cc: @pinaf

**Comment by pinaf** [comment]
@amihaiemil Just ask the ticket creator @yegor256 to close it.

**Comment by amihaiemil** [comment]
@pinaf Ok, I thought maybe rultor needs to deploy the PR... in a previous task I had it was merge + deploy. 
@yegor256 Can you close this? Thanks

**Comment by yegor256** [comment]
@amihaiemil many thanks!

**Comment by yegor256** [comment]
@rultor release, tag is `0.27`

**Comment by amihaiemil** [comment]
@dmarkov I didn't receive the payment automatically when the task was closed. I suppose a payment ID has to be assigned first?

**Comment by dmarkov** [comment]
> @dmarkov The PR for this has been approved and merged today. Now it has to be deployed, I think, before closure. cc: @pinaf 

@amihaiemil @yegor256 please help us here

**Comment by dmarkov** [comment]
@amihaiemil I added **30 mins** to your account, many thanks for working with the project (AP-5Y9171600R121771G)! The completion time here was 288 hours and 37 mins.; +30 added to your rating, at the moment it is: [+30](http://www.netbout.com/b/36402?open=rating)
