### ISSUE TITLE
Add support for the issue (un)lock API

### ISSUE THREAD

**Issue by cvrebert** [jcabi/jcabi-github#1204]
- https://developer.github.com/v3/issues/#lock-an-issue
- https://developer.github.com/v3/issues/#unlock-an-issue

**Comment by dmarkov** [comment]
@yegor256 please pay attention to this issue ([par.21](http://at.teamed.io/policy.html#21))

**Comment by 0crat** [comment]
Job [#1204](https://github.com/jcabi/jcabi-github/issues/1204) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Thanks for your contribution, @cvrebert[/z](https://www.0crat.com/u/cvrebert)! If you would be a member of [the project](https://www.0crat.com/p/C9R53K5JA), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by 0crat** [comment]
The job [#1204](https://github.com/jcabi/jcabi-github/issues/1204) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C9R53K5JA/2568e19c-566e-422a-aaa3-3814a3f02e1e); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@cvrebert Merged, please close

**Comment by paulodamaso** [comment]
@0crat wait for closure

**Comment by 0crat** [comment]
> @0crat wait for closure ([here](https://github.com/jcabi/jcabi-github/issues/1204#issuecomment-449954010))

@paulodamaso The impediment for [#1204](https://github.com/jcabi/jcabi-github/issues/1204) was registered successfully by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by amihaiemil** [comment]
@paulodamaso thanks :)

**Comment by 0crat** [comment]
The job [#1204](https://github.com/jcabi/jcabi-github/issues/1204) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0pdd** [comment]
@cvrebert the puzzle [#1474](https://github.com/jcabi/jcabi-github/issues/1474) is still not solved; solved: [#1462](https://github.com/jcabi/jcabi-github/issues/1462).

**Comment by 0pdd** [comment]
@cvrebert all 2 puzzles are solved here: [#1462](https://github.com/jcabi/jcabi-github/issues/1462), [#1474](https://github.com/jcabi/jcabi-github/issues/1474).
