### ISSUE TITLE
Can't support the combination query

### ISSUE THREAD

**Issue by linxingyun** [jcabi/jcabi-github#1205]
When using the combination query like below, there is no result return:

```
final JsonResponse resp = github.entry()
	            .uri().path("/search/users")
	            .queryParam("q", "location:china+created:<2009-01-01").back()
	            .fetch()
	            .as(JsonResponse.class);
```

It seems the url as encode can't be supported, which result in failure search. Could you please help to take a look at this? Thanks!

**Comment by linxingyun** [comment]
If I open the following URL in chrome, it could return the expected json data. But if use the jcabi-github api as mentioned above, it return with the failure message.

https://api.github.com/search/users?q=location:china+created:<2009-01-01

**Comment by dmarkov** [comment]
@yegor256 dispatch this issue please, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@linxingyun can you post the message/exception you're getting?

**Comment by linxingyun** [comment]
Here is the all content as return from "resp":

200 OK [https://api.github.com/search/users?q=location:china%2Bcreated:%3C2009-01-01]
Server: GitHub.com
Date: Wed, 02 Mar 2016 14:02:23 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Status: 200 OK
X-RateLimit-Limit: 10
X-RateLimit-Remaining: 9
X-RateLimit-Reset: 1456927403
Cache-Control: no-cache
X-GitHub-Media-Type: github.v3
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
Access-Control-Allow-Origin: *
Content-Security-Policy: default-src 'none'
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
Vary: Accept-Encoding
X-Served-By: dc1ce2bfb41810a06c705e83b388572d
X-GitHub-Request-Id: 7B746ED2:1A4DB:34C1D5:56D6F26D

{"total_count":0,"incomplete_results":false,"items":[]}

**Comment by linxingyun** [comment]
From the url as posted above, the URI automatically encode the '+' character as '%2B':
encode "https://api.github.com/search/users?q=location:china+created:<2009-01-01" to "https://api.github.com/search/users?q=location:china%2Bcreated:%3C2009-01-01".

As I open the both two url in chrome, the first one ("https://api.github.com/search/users?q=location:china+created:<2009-01-01") could return expected json result, while for the second one ("https://api.github.com/search/users?q=location:china%2Bcreated:%3C2009-01-01"), it return with the incorrect result (total_count as 0).
So it seems the GITHUB server can't accept the encoded code (as URI encoded) of '%2B' for character '+'. 
Could 'jcabi-github' api has work-around for this? Thanks!

**Comment by linxingyun** [comment]
@yegor256  please see the detail as posted above. Thanks!

**Comment by yegor256** [comment]
@linxingyun use it like this:

```
.queryParam("q", "location:china created:<2009-01-01")
```

**Comment by linxingyun** [comment]
@yegor256  Thanks a lot! It works fine now.

**Comment by yegor256** [comment]
@linxingyun please, close the issue. thanks for using our lib!
