### ISSUE TITLE
Is there option to set the timeout value?

### ISSUE THREAD

**Issue by linxingyun** [jcabi/jcabi-github#1219]
When the network is not stable, the application just seems to be hang there during fetch the JsonResponse from Github even after the network get recovery.  So I am getting question on is there an option in  jcabi-github lib to set the timeout value, so that we could handle it when the network is not fine? Thanks a lot!

**Comment by linxingyun** [comment]
@yegor256   Thanks!

**Comment by yegor256** [comment]
@linxingyun I think you can:

```
Github github = new RtGithub(
  new RtGithub().entry().timeout(connect, read)
);
```

More details in [jcabi-http](http.jcabi.com) (this is where that `Request` is coming from).

**Comment by linxingyun** [comment]
Thanks @yegor256 !
It seems the "jcabi-http"  as packaged in"jcabi-github-0.23-jar-with-dependencies.jar" is not up to date? Since using the timeout() method for com.jcabi.http.Request with "jcabi-github-0.23-jar-with-dependencies.jar" will bring the following build error:

The method timeout(int, int) is undefined for the type Request.
