### ISSUE TITLE
Javadoc out of date

### ISSUE THREAD

**Issue by davidsowerby** [jcabi/jcabi-github#1221]
Javadoc for MkGithub is out of date and a bit misleading:

>Github github = new MkGithub(new MkStorage.InFile(file), "jeff");
  github.repos().create("jcabi/jcabi-github");
  Repo repo = github.repos().get("jcabi/jcabi-github");
  Issues issues = repo.issues();
  Issue issue = issues.post("issue title", "issue body")

It should be something like:

>GitHub gitHub = new MkGithub("username");
Repos.RepoCreate repoCreate=new Repos.RepoCreate("dummy",false)
Repo repo = gitHub.repos().create(repoCreate)
repo.issues().create("title","body")

**Comment by dmarkov** [comment]
@yegor256 please do something about it, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@davidsowerby fixed in 514a106 thanks!
