### ISSUE TITLE
Class to get an oauth token from github

### ISSUE THREAD

**Issue by amihaiemil** [jcabi/jcabi-github#1223]
It would be useful to have a class that knows how to make an http POST to 

https://github.com/login/oauth/access_token

with params ``client_id, redirect_uri, client_secret and code`` . This way the api entrance with a token would be something like: 

``new RtGithub(new RtGithubToken(params).accessToken()) ...``

I think it would help clients refactor their code a lot.

**Comment by dmarkov** [comment]
@yegor256 take a look at this issue please and dispatch it somehow, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by amihaiemil** [comment]
@yegor256 can u pls have a look here? Thanks

**Comment by yegor256** [comment]
@amihaiemil this doesn't look like part of the GitHub API. it's something else, which is outside of scope of this project. I agree, it's a nice feature to have, but not in this project.
