### ISSUE TITLE
Implement Jobs API?

### ISSUE THREAD

**Issue by amihaiemil** [jcabi/jcabi-github#1227]
Github also offers an API for jobs - wouldn't it be a plus to have it? 

https://jobs.github.com/api

**Comment by dmarkov** [comment]
@yegor256 please take a look at it and dispatch (see [par.21](http://at.teamed.io/policy.html#21))

**Comment by amihaiemil** [comment]
@yegor256 ping

**Comment by amihaiemil** [comment]
@yegor256 what do you think here?

**Comment by yegor256** [comment]
@amihaiemil I don't think we need that. it seems to be a bit "outside" of GitHub API
