### ISSUE TITLE
Implement reactions API?

### ISSUE THREAD

**Issue by amihaiemil** [jcabi/jcabi-github#1230]
Github recently introduced Reactions API. We could start implementing it.

https://developer.github.com/v3/reactions/#list-reactions-for-a-commit-comment

**Comment by dmarkov** [comment]
@yegor256 please dispatch this issue

**Comment by amihaiemil** [comment]
@yegor256 can u have a look here? Thanks

**Comment by amihaiemil** [comment]
@yegor256 ping

**Comment by dmarkov** [comment]
@amihaiemil thanks for this report, I added 15 mins to your account, in transaction `AP-0E1142025P4024845`

**Comment by 0crat** [comment]
Job [#1230](https://github.com/jcabi/jcabi-github/issues/1230) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
The job [#1230](https://github.com/jcabi/jcabi-github/issues/1230) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C9R53K5JA/e4f25672-b1a5-4d22-be57-8f5cbcb7920a); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by paulodamaso** [comment]
@0crat wait for #1449 review

**Comment by 0crat** [comment]
> @0crat wait for #1449 review ([here](https://github.com/jcabi/jcabi-github/issues/1230#issuecomment-446034644))

@paulodamaso The impediment for [#1230](https://github.com/jcabi/jcabi-github/issues/1230) was registered successfully by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0pdd** [comment]
@amihaiemil the puzzle [#1451](https://github.com/jcabi/jcabi-github/issues/1451) is still not solved.

**Comment by 0crat** [comment]
The job [#1230](https://github.com/jcabi/jcabi-github/issues/1230) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0pdd** [comment]
@amihaiemil 5 puzzles [#1466](https://github.com/jcabi/jcabi-github/issues/1466), [#1467](https://github.com/jcabi/jcabi-github/issues/1467), [#1468](https://github.com/jcabi/jcabi-github/issues/1468), [#1469](https://github.com/jcabi/jcabi-github/issues/1469), [#1470](https://github.com/jcabi/jcabi-github/issues/1470) are still not solved; solved: [#1451](https://github.com/jcabi/jcabi-github/issues/1451).

**Comment by 0pdd** [comment]
@amihaiemil 4 puzzles [#1467](https://github.com/jcabi/jcabi-github/issues/1467), [#1468](https://github.com/jcabi/jcabi-github/issues/1468), [#1469](https://github.com/jcabi/jcabi-github/issues/1469), [#1470](https://github.com/jcabi/jcabi-github/issues/1470) are still not solved; solved: [#1451](https://github.com/jcabi/jcabi-github/issues/1451), [#1466](https://github.com/jcabi/jcabi-github/issues/1466).

**Comment by 0pdd** [comment]
@amihaiemil 4 puzzles [#1467](https://github.com/jcabi/jcabi-github/issues/1467), [#1468](https://github.com/jcabi/jcabi-github/issues/1468), [#1470](https://github.com/jcabi/jcabi-github/issues/1470), [#1476](https://github.com/jcabi/jcabi-github/issues/1476) are still not solved; solved: [#1451](https://github.com/jcabi/jcabi-github/issues/1451), [#1466](https://github.com/jcabi/jcabi-github/issues/1466), [#1469](https://github.com/jcabi/jcabi-github/issues/1469).

**Comment by 0pdd** [comment]
@amihaiemil 5 puzzles [#1467](https://github.com/jcabi/jcabi-github/issues/1467), [#1468](https://github.com/jcabi/jcabi-github/issues/1468), [#1470](https://github.com/jcabi/jcabi-github/issues/1470), [#1476](https://github.com/jcabi/jcabi-github/issues/1476), [#1477](https://github.com/jcabi/jcabi-github/issues/1477) are still not solved; solved: [#1451](https://github.com/jcabi/jcabi-github/issues/1451), [#1466](https://github.com/jcabi/jcabi-github/issues/1466), [#1469](https://github.com/jcabi/jcabi-github/issues/1469).

**Comment by 0pdd** [comment]
@amihaiemil 4 puzzles [#1467](https://github.com/jcabi/jcabi-github/issues/1467), [#1470](https://github.com/jcabi/jcabi-github/issues/1470), [#1476](https://github.com/jcabi/jcabi-github/issues/1476), [#1477](https://github.com/jcabi/jcabi-github/issues/1477) are still not solved; solved: [#1451](https://github.com/jcabi/jcabi-github/issues/1451), [#1466](https://github.com/jcabi/jcabi-github/issues/1466), [#1468](https://github.com/jcabi/jcabi-github/issues/1468), [#1469](https://github.com/jcabi/jcabi-github/issues/1469).

**Comment by 0pdd** [comment]
@amihaiemil 3 puzzles [#1470](https://github.com/jcabi/jcabi-github/issues/1470), [#1476](https://github.com/jcabi/jcabi-github/issues/1476), [#1483](https://github.com/jcabi/jcabi-github/issues/1483) are still not solved; solved: [#1451](https://github.com/jcabi/jcabi-github/issues/1451), [#1466](https://github.com/jcabi/jcabi-github/issues/1466), [#1467](https://github.com/jcabi/jcabi-github/issues/1467), [#1468](https://github.com/jcabi/jcabi-github/issues/1468), [#1469](https://github.com/jcabi/jcabi-github/issues/1469), [#1477](https://github.com/jcabi/jcabi-github/issues/1477).

**Comment by 0pdd** [comment]
@amihaiemil 2 puzzles [#1476](https://github.com/jcabi/jcabi-github/issues/1476), [#1483](https://github.com/jcabi/jcabi-github/issues/1483) are still not solved; solved: [#1451](https://github.com/jcabi/jcabi-github/issues/1451), [#1466](https://github.com/jcabi/jcabi-github/issues/1466), [#1467](https://github.com/jcabi/jcabi-github/issues/1467), [#1468](https://github.com/jcabi/jcabi-github/issues/1468), [#1469](https://github.com/jcabi/jcabi-github/issues/1469), [#1470](https://github.com/jcabi/jcabi-github/issues/1470), [#1477](https://github.com/jcabi/jcabi-github/issues/1477).

**Comment by 0pdd** [comment]
@amihaiemil the puzzle [#1476](https://github.com/jcabi/jcabi-github/issues/1476) is still not solved; solved: [#1451](https://github.com/jcabi/jcabi-github/issues/1451), [#1466](https://github.com/jcabi/jcabi-github/issues/1466), [#1467](https://github.com/jcabi/jcabi-github/issues/1467), [#1468](https://github.com/jcabi/jcabi-github/issues/1468), [#1469](https://github.com/jcabi/jcabi-github/issues/1469), [#1470](https://github.com/jcabi/jcabi-github/issues/1470), [#1477](https://github.com/jcabi/jcabi-github/issues/1477), [#1483](https://github.com/jcabi/jcabi-github/issues/1483).
