### ISSUE TITLE
Handle the authority by create issue 

### ISSUE THREAD

**Issue by motokito** [jcabi/jcabi-github#1238]
Hiho everyone,
I need some helps about using this github api.
I have created successful issues on my repo. But the problem is:
How can I catch the 404 Unauthorized user error to handle it, if the user data it's not correctly ? Or how can I compare the user data with githubs user data ?
It will be nice if someone give me some tipp or solution. 
Thx first 😊😊😊

**Comment by motokito** [comment]
Have someone a solution 😊 thx very much

**Comment by dmarkov** [comment]
@yegor256 please do something about this issue

**Comment by yegor256** [comment]
@motokito can you show the code you have already?

**Comment by motokito** [comment]
Thx you for your help. But i have found one of other solution. But i am very thx about your write back :smiley:
