### ISSUE TITLE
Unhandled API deprecations

### ISSUE THREAD

**Issue by amihaiemil** [jcabi/jcabi-github#1240]
As mentioned [here](https://developer.github.com/v3/versions/#v3-deprecations) there are 25 deprecations which are still supported, but will be removed in the next major release. 

Of the 25 points, I found 3 that need to be fixed (points 17, 19 and 25); 

17) User.bio() can be removed or marked with ``@ Deprecated`` since it's obsolete

19) User.gravatar() can be removed or marked with ``@ Deprecated``

25) Attribute "assignee" of an Issue becomes "assignees" - this needs a little more attention; it's work in ``MkIssue`` and ``Issue.Smart`` -> for instance ``Issue.assignee() : User`` becomes ``Issue.assignees() : List<User>`` and also ``Issue.Smart.assign(String)`` needs to be redesigned etc

**Comment by dmarkov** [comment]
@yegor256 please do something about this issue

**Comment by yegor256** [comment]
@amihaiemil I would suggest to report these problem separately, in different tickets.

**Comment by amihaiemil** [comment]
@yegor256 I opened #1243 , #1244 and #1245

**Comment by yegor256** [comment]
@amihaiemil thanks
