### ISSUE TITLE
User.bio() is deprecated

### ISSUE THREAD

**Issue by amihaiemil** [jcabi/jcabi-github#1243]
**User.bio()** is deprecated as mentioned [here](https://developer.github.com/v3/versions/#v3-deprecations) (point 17) and will be removed in a future major release.

Thus, it should removed from our lib

**Comment by dmarkov** [comment]
@yegor256 please do something about it, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by amihaiemil** [comment]
@yegor256 what about here?

**Comment by amihaiemil** [comment]
@yegor256 ping

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-github#1243` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
