### ISSUE TITLE
User.gravatar() deprecated

### ISSUE THREAD

**Issue by amihaiemil** [jcabi/jcabi-github#1244]
User.gravatar() will be removed in the next major release of the Github API, as mentioned [here](https://developer.github.com/v3/versions/#v3-deprecations) (point 19).

Thus, it should be removed.

**Comment by dmarkov** [comment]
@yegor256 please take a look at it and dispatch (see [par.21](http://at.teamed.io/policy.html#21))

**Comment by yegor256** [comment]
@amihaiemil we should just remove it, thanks

**Comment by dmarkov** [comment]
@amihaiemil many thanks for the bug report, I added 15 mins to your acc, transaction `AP-70Y152811X113963H`

**Comment by 0crat** [comment]
Job [#1244](https://github.com/jcabi/jcabi-github/issues/1244) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
The job [#1244](https://github.com/jcabi/jcabi-github/issues/1244) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C9R53K5JA/31242bbd-bdce-49f9-9a95-1a22243324ae); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
The job [#1244](https://github.com/jcabi/jcabi-github/issues/1244) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)
