### ISSUE TITLE
Get rid of Manifest.mf attributes?

### ISSUE THREAD

**Issue by amihaiemil** [jcabi/jcabi-github#1246]
Maybe it would be better to get rid of the manifest.MF attributes and read the 3 parameters from a property file instead? Other users reported issues because the parameters weren't found, and also I encountered the issue with the latest version (I had to hardcode the values in my project's manifest.mf, using assembly-plugin). 

If you write the 3 values in a properties file under src/main/resources, and read them from there, then it should work.

**Comment by dmarkov** [comment]
@yegor256 please take a look at it and dispatch (see [par.21](http://at.teamed.io/policy.html#21))

**Comment by yegor256** [comment]
@amihaiemil but `MANIFEST.MF` is shipped inside the JAR file. Why this is a problem? Please explain more, I don't get it

**Comment by amihaiemil** [comment]
@yegor256 yes, the Manifest.MF is shipped with the jar, but at runtime the code looks in the ``.war``'s Manifest.MF, doesn't go down the dependency tree to look in the jar's manifest.mf
More precisely, the code looks in this Manifest.MF:

![image](https://cloud.githubusercontent.com/assets/6305156/20514714/31bfadc8-b096-11e6-893d-c501cd039481.png)

while the 3 attributes are found in this one:

![image](https://cloud.githubusercontent.com/assets/6305156/20514735/5c1cc61e-b096-11e6-8473-b8b21a050af1.png)



The point is, I had to hardcode the 3 attribtues in the ``.war``'s Manifest.MF, using maven's assembly plugin (see [here](https://github.com/opencharles/charles-github-ejb/blob/master/charles-rest/pom.xml#L30))- and others had this exact issue as well, see [here](https://github.com/jcabi/jcabi-github/issues/1198)

**Comment by yegor256** [comment]
@amihaiemil got it. You're right, let's move to `.properties`

**Comment by 0crat** [comment]
The job [#1246](https://github.com/jcabi/jcabi-github/issues/1246) assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/C9R53K5JA/931141144); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-github#1246` already assigned to @amihaiemil, can't assign to @amihaiemil

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
The job [#1246](https://github.com/jcabi/jcabi-github/issues/1246) is now out of scope
