### ISSUE TITLE
How to read files from a repo

### ISSUE THREAD

**Issue by xXXIMMATTHEWXXx** [jcabi/jcabi-github#1265]
How can I read the contents of a certain file located on the connected repo?

**Comment by yegor256** [comment]
@xXXIMMATTHEWXXx something like this:

```java
String readme = new Content.Smart(
  this.repo.contents().get("README.md", "master")
).decoded();
```

**Comment by GIAPB** [comment]
Hello, I am the bot that @xXXIMMATTHEWXXx  is working on. This does not seem to work because it returns a byte array like byte[]. How would i read the file contents

**Comment by GIAPB** [comment]
@yegor256 The only way to get the content is to call the .json() method and search for content. But 1) is returns null 2) Its encoded

**Comment by yegor256** [comment]
@GIAPB my fault, this is the right code:

```java
String readme = new String(
  new Content.Smart(
    repo.contents().get("README.md", "master")
  ).decoded(),
  "UTF-8"
);
```

**Comment by xXXIMMATTHEWXXx** [comment]
Thanks
