### ISSUE TITLE
How do i loop through all current issues 

### ISSUE THREAD

**Issue by xXXIMMATTHEWXXx** [jcabi/jcabi-github#1266]
How do i loop through the current list of issues?
Here is my current code:
```java	
Logging.info("==== Job: Issue is starting ====");
Github github = new RtGithub(Giapb.githubAPIKey);
Repo repo = github.repos().get(new Coordinates.Simple(Giapb.owner, Giapb.repo));
Issues issues = repo.issues();
```
I tried .iterate() but i cant get it to work. Any examples?

**Comment by xXXIMMATTHEWXXx** [comment]
Also how do I loop through the lablels of the issue ?

**Comment by yegor256** [comment]
@xXXIMMATTHEWXXx I guess you need something like this (pseudo-code):

```
repo.issues.iterate(
  {"state": "all"}
);
```

See: https://developer.github.com/v3/issues/#list-issues-for-a-repository
