### ISSUE TITLE
Cannot build correctly via gradle

### ISSUE THREAD

**Issue by TheWithz** [jcabi/jcabi-github#1272]
`compile 'com.jcabi:jcabi-github:0.23'`

https://hastebin.com/asuharekag.swift

Not sure what happened. It was working fine, and then exploded. I looked through the stack trace and couldn't find the root cause of the issue. 

EDIT 1: 
this is the error output 
> :compileJava FAILED

> FAILURE: Build failed with an exception.

> What went wrong:
> Could not resolve all dependencies for configuration :compileClasspath.
> Could not resolve com.jcabi:jcabi-github:0.23.
  Required by:
      project :
   > Could not resolve com.jcabi:jcabi-github:0.23.
      > Could not parse POM http://jcenter.bintray.com/com/jcabi/jcabi-github/0.23/jcabi-github-0.23.pom
         > Could not resolve com.jcabi:jcabi:1.17.
            > Could not resolve com.jcabi:jcabi:1.17.
               > Could not parse POM http://jcenter.bintray.com/com/jcabi/jcabi/1.17/jcabi-1.17.pom
                  > Could not resolve com.jcabi:parent:0.32.1.
                     > Could not resolve com.jcabi:parent:0.32.1.
                        > Could not parse POM http://jcenter.bintray.com/com/jcabi/parent/0.32.1/parent-0.32.1.pom
                           > Invalid byte 1 of 1-byte UTF-8 sequence.

> Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

>BUILD FAILED

>Total time: 0.925 secs

EDIT 2: 
using version 0.29 "the latest version i could find" gives this
https://hastebin.com/jimelodipe.rb

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@TheWithz can you just try again? Looks like a network error to me.

**Comment by amihaiemil** [comment]
Closing as we have no development here. Feel free to reopen if the issue appears again.

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-github#1272` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
