### ISSUE TITLE
HTTP 302 Issued from GitHub results in failure

### ISSUE THREAD

**Issue by jdjasperson** [jcabi/jcabi-github#1275]
When GitHub issues an HTTP 302 response, the jcabi library creates an exception rather than following the redirect link located in the `Location` response header.  A 302 response is being incorrectly interpreted as an error, when it is not.

Below is the relevant message in the stack trace; I've removed my organization and repo information.  This is a private, enterprise level repository.
> Exception in thread "main" java.lang.AssertionError: HTTP response status is not equal to 200:
302 Found [https://api.github.com/repos/_MyOrganization_/_MyRepository_/contents/config/?ref=master]
> Location: https://api.github.com/repositories/82982095/contents/config

Here's the relevant excerpt from the GitHub developer documentation:
https://developer.github.com/v3/#http-redirects

> API v3 uses HTTP redirection where appropriate. Clients should assume that any request may result in a redirection. Receiving an HTTP redirection is not an error and clients should follow that redirect. Redirect responses will have a `Location` header field which contains the URI of the resource to which the client should repeat the requests.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@jdjasperson thanks for reporting this, definitely a bug on our side. Let me try to fix it

**Comment by yegor256** [comment]
@rultor release, tag is `0.31`

**Comment by yegor256** [comment]
@rultor release, tag is `0.31`

**Comment by yegor256** [comment]
@rultor release, tag is `0.31`

**Comment by yegor256** [comment]
@rultor release, tag is `0.31`

**Comment by amihaiemil** [comment]
@yegor256 Don't you think this should be implemented in jcabi-http rather than here? :D It's the job of the http-client to follow 302 Location, after all.

**Comment by yegor256** [comment]
@rultor release, tag is `0.31`

**Comment by yegor256** [comment]
@jdjasperson should be fine now, try version 0.31 and close the ticket if it works. Thanks!

**Comment by yegor256** [comment]
@amihaiemil not really. The HTTP client should be generic. Not always you need to follow 30x redirects. Sometimes (very often) you just need to get the answer as is, and never follow the `Location`.

**Comment by amihaiemil** [comment]
This seems to be solved, so I'm closing it. Feel free to reopen if the issue appears again.

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-github#1275` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
