### ISSUE TITLE
RtBranch.java:75-76: Refactor to reduce number of...

### ISSUE THREAD

**Issue by 0pdd** [jcabi/jcabi-github#1301]
The puzzle `1085-6b1095b1` in [`src/main/java/com/jcabi/github/RtBranch.java`](https://github.com/jcabi/jcabi-github/blob/master/src/main/java/com/jcabi/github/RtBranch.java) (lines 75-76) has to be resolved: Refactor to reduce number of arguments to avoid ParameterNumberCheck warning.

The puzzle was created by Chris Rebert on 26-May-15. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html).

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1301](https://github.com/jcabi/jcabi-github/issues/1301) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1301](https://github.com/jcabi/jcabi-github/issues/1301) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C9R53K5JA/e3aa1690-c23e-4557-93ec-c3884ffcae4b); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-github#1301` already assigned to @paulodamaso, can't assign to @paulodamaso

**Comment by amihaiemil** [comment]
@paulodamaso only do the refactoring if it's possible without many changes. If many changes are required, then just remove the puzzle and let's leave it like that :)

**Comment by paulodamaso** [comment]
@amihaiemil Well I don't see why refactor it for start. I think that this class is cohesive enough as it is, and this check is being too hard on it in my opinion.

Actually I think that an ideal number for this check would be 5 parameters, 3 I think that is very little.

**Comment by amihaiemil** [comment]
@paulodamaso right, makes sense. Then just remove the puzzle (let's not increase the number of params for now) :)

**Comment by paulodamaso** [comment]
@0crat wait for #1450 merge

**Comment by 0crat** [comment]
> @0crat wait for #1450 merge ([here](https://github.com/jcabi/jcabi-github/issues/1301#issuecomment-446034501))

@paulodamaso The impediment for [#1301](https://github.com/jcabi/jcabi-github/issues/1301) was registered successfully by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by paulodamaso** [comment]
@amihaiemil Something weird happened, I've removed the puzzle but 0pdd did not closed the issue

**Comment by paulodamaso** [comment]
@amihaiemil please close

**Comment by amihaiemil** [comment]
@paulodamaso I can try but then I think 0crat will complain and won't make any payments -- it is mandatory that the ticket's reporter closes it.

**Comment by amihaiemil** [comment]
@paulodamaso if no payments are made, I'll boost one of your future task and it will make up for it :)

**Comment by paulodamaso** [comment]
@amihaiemil Don't worry, but why didn't 0pdd closed it?

**Comment by amihaiemil** [comment]
@paulodamaso no idea. I changed the config now, so I will receive alerts in the future, if something goes wrong: https://github.com/jcabi/jcabi-github/blob/master/.0pdd.yml
