### ISSUE TITLE
Hooks.java:88-90: Add support for the "events"...

### ISSUE THREAD

**Issue by 0pdd** [jcabi/jcabi-github#1309]
The puzzle `1106-3aa88d70` in [`src/main/java/com/jcabi/github/Hooks.java`](https://github.com/jcabi/jcabi-github/blob/master/src/main/java/com/jcabi/github/Hooks.java) (lines 88-90) has to be resolved: Add support for the "events" parameter of the hook creation API. It's a list of strings of the names of events which the hook will be triggered for.

The puzzle was created by Chris Rebert on 05-Jun-15. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and
[about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-github#1309` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
