### ISSUE TITLE
Webhooks request end points

### ISSUE THREAD

**Issue by jcamiloradamesa** [jcabi/jcabi-github#1322]
Hello Guys

I am wondering if is possible to use jcabi in order to create GitHub web hooks end points (custom end points which accept web hooks calls).  Usually this end points implemented with Jersey or Spring MVC use models classes that match request json (not compatible with jcabi idea I think), as an alternative I was thinking to obtain  request json and obtain instance i.e of `Pull` as  [RtPull](https://github.com/jcabi/jcabi-github/blob/647243cc5f0451398fde2fbccd7cb50a29dcdfa1/src/main/java/com/jcabi/github/RtPull.java)  but this class is package private and can not be used.

Is web hooks "listeners" feature supported by jcabi-github?

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@jcamiloradamesa this is outside of the scope of this project. You just need to parse them using any JSON parser and _then_ connect to GitHub API, if you need to.

**Comment by jcamiloradamesa** [comment]
@yegor256 thanks, appreciate quick response and clarification

**Comment by 0crat** [comment]
Oops! Job `gh:jcabi/jcabi-github#1322` was not in scope
