### ISSUE TITLE
Mock pull request created by MkGithub is not a pull according to Issue.Smart.isPull()

### ISSUE THREAD

**Issue by carlosmiranda** [jcabi/jcabi-github#1323]
The unit test below fails:

```java
    @Test
    public void mkPullIsAPullAccordingToIssueSmart() throws Exception {
        final Repo repo = new MkGithub().randomRepo();
        final Pull pull = repo.pulls().create(
            "hello",
            "head-branch",
            "base-branch"
        );
        final Issue.Smart issue = new Issue.Smart(
            repo.issues().get(pull.number())
        );
        MatcherAssert.assertThat(
            issue.isPull(),
            Matchers.is(true)
        );
    }
```

Seeing that the issue referred to is actually a pull request, `issue.isPull()` should really return `true`.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@0crat assign @g4s8

**Comment by 0crat** [comment]
> @0crat assign @g4s8 ([here](https://github.com/jcabi/jcabi-github/issues/1323#issuecomment-320178255))

@yegor256 Job `gh:jcabi/jcabi-github#1323` assigned to @g4s8, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)). @g4s8 is not a member of this project yet, but can request to join. @g4s8 check your [Zerocracy profile](http://www.0crat.com/u/g4s8) and follow the instructions.

**Comment by 0crat** [comment]
+15 points just awarded to @carlosmiranda, total is [+255](http://www.0crat.com/u/carlosmiranda).

**Comment by g4s8** [comment]
> is not a member of this project yet, but can request to join. 

@yegor256 how can I join this project? I didn't find instructions on my profile page

**Comment by yegor256** [comment]
@g4s8 that's a bug, submit it to zerocracy GitHub, we'll fix

**Comment by g4s8** [comment]
@carlosmiranda it was fixed in #1323, can we close this?

**Comment by 0crat** [comment]
Are you speaking to me or about me? You must always start your message with my name if you want to address it to me.

**Comment by yegor256** [comment]
@rultor release, tag is `0.33.1`

**Comment by 0crat** [comment]
Are you speaking to me or about me? You must always start your message with my name if you want to address it to me.

**Comment by 0crat** [comment]
Are you speaking to me or about me? You must always start your message with my name if you want to address it to me.

**Comment by 0crat** [comment]
Are you speaking to me or about me? You must always start your message with my name if you want to address it to me.

**Comment by carlosmiranda** [comment]
@g4s8 thanks!

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-github#1323` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @g4s8, total is [+1965](http://www.0crat.com/u/g4s8).
