### ISSUE TITLE
Integration tests can fail due to abuse protection

### ISSUE THREAD

**Issue by g4s8** [jcabi/jcabi-github#1325]
Integration tests fails with 403 forbidden error when accessing Github API:
```json
{
  "documentation_url": "https://developer.github.com/v3/#abuse-rate-limits",
  "message": "You have triggered an abuse detection mechanism. Please wait a few minutes before you try again."
}
```
see this log for example: http://www.rultor.com/t/12587-320468783

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/jcabi/jcabi-github/issues/1325#issuecomment-320526525))

@yegor256 Job `gh:jcabi/jcabi-github#1325` is in scope.

**Comment by 0crat** [comment]
+15 points just awarded to @g4s8, total is [+780](http://www.0crat.com/u/g4s8).

**Comment by yegor256** [comment]
@g4s8 it's fixed already, they are disabled for Rultor and Travis.

**Comment by 0crat** [comment]
Are you speaking to me or about me? You must always start your message with my name if you want to address it to me.

**Comment by g4s8** [comment]
@yegor256 thanks, now it merged

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-github#1325` is now out of scope.

**Comment by 0crat** [comment]
Are you speaking to me or about me? You must always start your message with my name if you want to address it to me.
