### ISSUE TITLE
Pull Request Iterator Parameters

### ISSUE THREAD

**Issue by chbrown13** [jcabi/jcabi-github#1330]
I am trying to get a list of pull requests for a repository with any status, open or closed, however I can only get opened pull requests when iterating through a repo's PRs even when passing in "all" or "closed" as a parameter.

```
ArrayList<Pull.Smart> requests = new ArrayList<Pull.Smart>();
Map<String, String> params = new HashMap<String, String>();
params.put("status", "all");
Iterator<Pull> pullit = this.repo.pulls().iterate(params).iterator();
while (pullit.hasNext()) { // still only iterates through open pull requests
    Pull.Smart pull = new Pull.Smart(pullit.next());
    requests.add(pull);
}
```

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@chbrown13 are you sure? The code looks correct, we do pass parameters to GitHub: https://github.com/jcabi/jcabi-github/blob/master/src/main/java/com/jcabi/github/RtPulls.java#L129

**Comment by chbrown13** [comment]
Ok gotcha, yes I'm sure this is happening.

**Comment by chbrown13** [comment]
@yegor256 For example in the screenshot below I'm specifically looking for "closed" PRs in a test repo and previously closed pull request 22. However when iterating through and printing PR numbers everything except 22 is returned.

![image](https://user-images.githubusercontent.com/4522684/31340154-464e5304-acd3-11e7-90e1-02a8f436bd05.png)

**Comment by yegor256** [comment]
@chbrown13 it's `state`, not `status`: https://developer.github.com/v3/pulls/#list-pull-requests

**Comment by chbrown13** [comment]
Thanks @yegor256

**Comment by 0crat** [comment]
Oops! Job `gh:jcabi/jcabi-github#1330` was not in scope
