### ISSUE TITLE
bug when obtaining Smart.Commit#message() 

### ISSUE THREAD

**Issue by pgressa** [jcabi/jcabi-github#1348]
Code says:
```
 public String message() throws IOException {
            return this.jsn.json().getJsonObject("commit").getString("message");
        }
```

But the truth is that the message is not part of the commit element. I'm able to obtain the message when calling:
```
commit.json().getString("message")
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@pgressa we had it the way you are suggesting, but fixed in a9b7000f2044f8b6872bfcb7153ef91a4eba3041

**Comment by yegor256** [comment]
@pgressa what do you think? Which one is right?)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually or invite more people to the project, as explained in [§51](http://www.zerocracy.com/policy.html#51)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually or invite more people to the project, as explained in [§51](http://www.zerocracy.com/policy.html#51)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually or invite more people to the project, as explained in [§51](http://www.zerocracy.com/policy.html#51)

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-github#1348` is not assigned, can't get performer

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) resigned from [#1348](https://github.com/jcabi/jcabi-github/issues/1348), since the job is not in scope anymore
