### ISSUE TITLE
Ambiguous or missing domain logic for fetching User repositories

### ISSUE THREAD

**Issue by biboran** [jcabi/jcabi-github#1349]
`User` interface doesn't support fetching its `Repos`.

Is there any workaround for getting `Repos` for `github.users().self()` or does `Repos` currently mean `AllGithubRepos`?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@biboran dup of #1361

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
