### ISSUE TITLE
jdk9 failing

### ISSUE THREAD

**Issue by ashtonhogan** [jcabi/jcabi-github#1350]
```
Could not find artifact com.sun:tools:jar:1.7.0 at specified path C:\Program Files\Java\jdk9/../lib/tools.jar -> [Help 1]
```

Full log [here](https://ci.appveyor.com/api/buildjobs/lbw58i2uf4tf54uy/log)

Potential solution here: https://stackoverflow.com/questions/26422259/maven-missing-artifact-com-suntoolsjar1-6-0-compile-time-exception-in-pom-x

@appveyor

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by ashtonhogan** [comment]
bump
