### ISSUE TITLE
Issue.Smart doesn't have closedAt()

### ISSUE THREAD

**Issue by g4s8** [jcabi/jcabi-github#1352]
There is `closed_at` issue attribute in issue json-object: https://developer.github.com/v3/issues/#get-a-single-issue
which can say when exactly this issue was closed. Example: https://api.github.com/repos/jcabi/jcabi-github/issues/1
I think it can be included into `Issue.Smart` class

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, charge attention to this issue

**Comment by 0crat** [comment]
The job [#1352](https://github.com/jcabi/jcabi-github/issues/1352) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3RUBL5H9/721023682). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@g4s8 fixed in 5ee94841 and released as 0.34

**Comment by g4s8** [comment]
@yegor256 thanks!

**Comment by 0crat** [comment]
The job [#1352](https://github.com/jcabi/jcabi-github/issues/1352) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)
