### ISSUE TITLE
Can't check user existance

### ISSUE THREAD

**Issue by g4s8** [jcabi/jcabi-github#1359]
It's not possible to check whether exist user or not, now I need to fetch some data from user and check exception if user does not exist:
```java
try {
  new User.Smart(github.users().get("some-login")).id()
  // exists
} catch (Exception ex) {
  // doesn't exist
}
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#1359](https://github.com/jcabi/jcabi-github/issues/1359) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3RUBL5H9/720919735). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@g4s8 implemented in 32650b10 and released as 0.34

**Comment by g4s8** [comment]
@yegor256 thanks!

**Comment by 0crat** [comment]
The job [#1359](https://github.com/jcabi/jcabi-github/issues/1359) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)
