### ISSUE TITLE
MkReleases.create(String tag) should not prepopulate optional release attributes

### ISSUE THREAD

**Issue by llorllale** [jcabi/jcabi-github#1362]
This method is prepopulating all/a bunch of attributes of the fake release. This leads to surprises when used for tests because I do not expect the fake release to already have a body. I would expect the body to be `null` or maybe a blank string. The same thing goes for the release's title, etc.

This method should not prepopulate any optional attributes.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@llorllale do you want to contribute with a PR? This project has no funds, but we will appreciate your help.

**Comment by llorllale** [comment]
@yegor256 sure, I'll give it a shot

**Comment by llorllale** [comment]
Closing as solution was merged in PR #1368

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
