### ISSUE TITLE
Unable to mark an MkRelease with prerelease=true

### ISSUE THREAD

**Issue by llorllale** [jcabi/jcabi-github#1363]
Encountered this issue while writing tests in a separate project.

`Release.Smart#prerelease(boolean)` is not tested. I added the following in `MkReleaseTest` and notice that it fails as well:

```java
    @Test
    public void prerelease() throws Exception {
        final Release release = MkReleaseTest.release();
        final Release.Smart smart = new Release.Smart(release);
        smart.prerelease(true);
        MatcherAssert.assertThat(
            smart.prerelease(),
            Matchers.is(true)
        );
    }
```

Error is:

```
java.lang.AssertionError: 
Expected: is <true>
     but: was <false>
```

**Comment by yegor256** [comment]
@llorllale do you want to contribute with a PR? This project has no funds, but we will appreciate your help.

**Comment by llorllale** [comment]
@yegor256 sure, I'll give it a shot

**Comment by 0crat** [comment]
Job [#1363](https://github.com/jcabi/jcabi-github/issues/1363) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually or invite more people to the project, as explained in [§51](http://www.zerocracy.com/policy.html#51)

**Comment by llorllale** [comment]
@amihaiemil Seems like I can't work on this issue but I'm interested in its resolution so:

I've figured out the problem. The `Mk` implementations store the `prerelease` value *as a string*. 

Therefore, this method in `Release.Smart` fails:

```java
        /**
         * Get a property as boolean.
         * @param name Parameter name
         * @return Returns boolean property value
         * @throws IOException If there is any I/O problem
         */
        private boolean booleanValue(final String name) throws IOException {
            return JsonValue.TRUE.equals(this.json().get(name));
        }
```

The part `this.json().get(name)` will return a `JsonString`, not a `JsonValue.TRUE`, and hence it will never be equal. That `JsonString`'s value will be the *string* `true` or `false`.

I'm not so sure what's the most elegant way to fix this.

**Comment by llorllale** [comment]
@amihaiemil I think this simple hack should be ok:

```java
return Boolean.TRUE.equals(Boolean.parseBoolean(this.json().get(name).toString()));
```

**Comment by amihaiemil** [comment]
@llorllale I think the simplest way is:

```java
Boolean.TRUE.equals(this.json().getBoolean(name))
```

I will have a look over it this weekend, maybe I can solve it :)

**Comment by 0crat** [comment]
The job [#1363](https://github.com/jcabi/jcabi-github/issues/1363) assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/C9R53K5JA/1031160063); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0pdd** [comment]
@llorllale the puzzle [#1390](https://github.com/jcabi/jcabi-github/issues/1390) is still not solved.

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
The job [#1363](https://github.com/jcabi/jcabi-github/issues/1363) is now out of scope

**Comment by 0pdd** [comment]
@llorllale the only puzzle [#1390](https://github.com/jcabi/jcabi-github/issues/1390) is solved here.

**Comment by llorllale** [comment]
@amihaiemil maybe try releasing again? #1405 was merged after this release attempt

**Comment by amihaiemil** [comment]
@rultor release it, tag is `0.39`

**Comment by llorllale** [comment]
@amihaiemil thanks!
