### ISSUE TITLE
Bug: asymetrical processing of asset contents between MkReleaseAssets.upload() and MkReleaseAsset.raw()

### ISSUE THREAD

**Issue by llorllale** [jcabi/jcabi-github#1366]
**Context**
`MkReleaseAssets.upload()` stores the bytes as-is (in string form), while `MkReleaseAsset.raw()` will process the string with [DatatypeConverter.parseBase64Binary()](https://docs.oracle.com/javase/8/docs/api/javax/xml/bind/DatatypeConverter.html#parseBase64Binary-java.lang.String-). This despite the fact that `MkReleaseAssets` never encoded the bytes to base64 in the first place.

**Problem**
The contents returned by `MkReleaseAsset` will not match the expected bytes for any non-trivial input of bytes. This is because `DatatypeConverter.parseBase64Binary` will silently drop invalid characters as per the Base64 spec without throwing an error, and thus when you decode those bytes you'll end up with a different sequence of bytes.

**Test**
```java
    @Test
    public void test() throws Exception {
        final String test = "This is a test asset.";
        final ReleaseAsset asset = new MkGithub().randomRepo().releases()
          .create("v1.0")
          .assets()
          .upload(test.getBytes(), "type", "name");
        MatcherAssert.assertThat(
            DatatypeConverter.printBase64Binary(IOUtils.toByteArray(asset.raw())),
            Matchers.is(test)
        );
    }
```
Test error:
```
java.lang.AssertionError: 
Expected: is "This is a test asset."
     but: was "Thisisatestasset"
```

**References**
* [RFC-4648](http://www.rfc-editor.org/rfc/rfc4648.txt) Table 1: The Base 64 Alphabet
* [StackOverflow](https://stackoverflow.com/a/30708382/1623885)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1366](https://github.com/jcabi/jcabi-github/issues/1366) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by llorllale** [comment]
@amihaiemil this was fixed in PR #1367.

I opened this issue; can I just close it then?

**Comment by amihaiemil** [comment]
@llorllale yes, sure

**Comment by 0crat** [comment]
The job [#1366](https://github.com/jcabi/jcabi-github/issues/1366) is now out of scope
