### ISSUE TITLE
 test

### ISSUE THREAD

**Issue by PandaBoy444** [jcabi/jcabi-github#1371]

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
@pandaboy444[/z](https://www.0crat.com/u/pandaboy444) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C9R53K5JA) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
