### ISSUE TITLE
Release 0.37

### ISSUE THREAD

**Issue by amihaiemil** [jcabi/jcabi-github#1373]
Let's release ``0.37``, it has a few bug fixes, including a major change: user agent data is now read from properties file instead of Manifest.MF: https://github.com/jcabi/jcabi-github/issues/1246

**Comment by amihaiemil** [comment]
@rultor release, tag is `0.37`

**Comment by 0crat** [comment]
Job [#1373](https://github.com/jcabi/jcabi-github/issues/1373) is now in scope, role is `DEV`

**Comment by amihaiemil** [comment]
That test has to be fixed and only check for ``startsWith("jcabi-github ")``, since the version will always be different, at least at release time.

**Comment by 0crat** [comment]
The job [#1373](https://github.com/jcabi/jcabi-github/issues/1373) assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/C9R53K5JA/950825901); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-github#1373` already assigned to @amihaiemil, can't assign to @amihaiemil

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by amihaiemil** [comment]
@rultor release, tag is `0.37`

**Comment by amihaiemil** [comment]
@llorllale 0.37 is out :)

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
The job [#1373](https://github.com/jcabi/jcabi-github/issues/1373) is now out of scope
