### ISSUE TITLE
MkUser.java:56-57: Implement markAsRead(final Date...

### ISSUE THREAD

**Issue by 0pdd** [jcabi/jcabi-github#1375]
The puzzle `1305-b50fad21` from #1305 has to be resolved:

https://github.com/jcabi/jcabi-github/blob/42c24f097a546761d2df560928c9457d275c8df1/src/main/java/com/jcabi/github/mock/MkUser.java#L56-L57

The puzzle was created by George Aristy on 04-Apr-18. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
@0pdd[/z](https://www.0crat.com/u/0pdd) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C9R53K5JA) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
The job [#1375](https://github.com/jcabi/jcabi-github/issues/1375) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/C9R53K5JA/941542015); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by llorllale** [comment]
@amihaiemil quick question: does this method have to mark as read *starting* at the given date, or *up to* the given date?

```java
    /**
     * Marks notifications as read.
     * @param lastread Describes the last point that notifications were
     *  checked.
     * @see <a href="https://developer.github.com/v3/activity/notifications/#mark-as-read">Mark as read</a>
     */
    void markAsRead(final Date lastread);
```

**Comment by llorllale** [comment]
@amihaiemil ping

**Comment by amihaiemil** [comment]
@llorllale according to the API description, it is *up to that point*: https://developer.github.com/v3/activity/notifications/#mark-as-read

**Comment by 0pdd** [comment]
The puzzle `1305-b50fad21` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
The job [#1375](https://github.com/jcabi/jcabi-github/issues/1375) is now out of scope
