### ISSUE TITLE
Checkstyle issues

### ISSUE THREAD

**Issue by llorllale** [jcabi/jcabi-github#1395]
Fix checkstyle issues that are breaking the build as reported by rultor [here](https://github.com/jcabi/jcabi-github/pull/1392#issuecomment-382835439).

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by amihaiemil** [comment]
@0crat assign @llorllale

**Comment by llorllale** [comment]
@amihaiemil I guess we can close this?

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by llorllale** [comment]
@0crat waiting for ticket reporter to close the issue

**Comment by llorllale** [comment]
@amihaiemil can we close this?

**Comment by 0crat** [comment]
> @0crat waiting for ~ticket reporter~ @amihaiemil to close the issue ([here](https://github.com/jcabi/jcabi-github/issues/1395#issuecomment-384054616))

@llorllale The impediment for [#1395](https://github.com/jcabi/jcabi-github/issues/1395) was registered successfully by @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
The job [#1395](https://github.com/jcabi/jcabi-github/issues/1395) is now out of scope
