### ISSUE TITLE
RtUserTest.java:484-488: Un-ignore this test and...

### ISSUE THREAD

**Issue by 0pdd** [jcabi/jcabi-github#1401]
The puzzle `1304-efe7c280` from #1304 has to be resolved:

https://github.com/jcabi/jcabi-github/blob/5ded5a2945840694fc106994de7a374ee8968c8c/src/test/java/com/jcabi/github/RtUserTest.java#L484-L488

The puzzle was created by Mihai A on 25-Apr-18. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
@0pdd[/z](https://www.0crat.com/u/0pdd) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C9R53K5JA) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job [#1401](https://github.com/jcabi/jcabi-github/issues/1401) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1401](https://github.com/jcabi/jcabi-github/issues/1401) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/C9R53K5JA/1260896007); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by llorllale** [comment]
@amihaiemil what's wrong with using `FkRequest`?

**Comment by amihaiemil** [comment]
@llorllale I think ``FkRequest`` does not give you the option to specify the URI, it just calls ``localhost:80``, I believe. But if you use MkGrizzly http server, then you can mock URIs and their responses, and just use ``ApacheRequest`` with ``localhost:{grizzly_port}/mock/path`` to fake the request and get the response. 

This task originated from [this](https://github.com/jcabi/jcabi-github/pull/1391#discussion_r182836854) idea. We shouldn't use the ``Mk*`` classes in the library to test the ``Rt*`` classes :)

**Comment by amihaiemil** [comment]
@llorllale nevertheless, do it as simple as possible. If you find a way of using ``FkRequest`` and don't need the mock server, do it like that, I have no problem :D Just don't forget about PDD. This can be a research task as well, if you must study how ``MkGrizzly`` works in other tests.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by llorllale** [comment]
@0crat waiting on review/merge for #1411

**Comment by 0crat** [comment]
> @0crat waiting on review/merge for #1411 ([here](https://github.com/jcabi/jcabi-github/issues/1401#issuecomment-388945284))

@llorllale The impediment for [#1401](https://github.com/jcabi/jcabi-github/issues/1401) was registered successfully by @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0pdd** [comment]
The puzzle `1304-efe7c280` has disappeared from the source code, that's why I closed this issue.
