### ISSUE TITLE
Checkstyle failures again

### ISSUE THREAD

**Issue by amihaiemil** [jcabi/jcabi-github#1403]
Qulice seems to complain again about some checkstyle rules, see [here](https://github.com/jcabi/jcabi-github/issues/1363#issuecomment-386536107)

**Comment by 0crat** [comment]
Job [#1403](https://github.com/jcabi/jcabi-github/issues/1403) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
The job [#1403](https://github.com/jcabi/jcabi-github/issues/1403) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/C9R53K5JA/1270675877); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by llorllale** [comment]
@amihaiemil I believe I fixed these in #1405

**Comment by llorllale** [comment]
@0crat waiting

**Comment by amihaiemil** [comment]
@llorllale I see, ok :)

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/jcabi/jcabi-github/issues/1403#issuecomment-387483392))

@llorllale The impediment for [#1403](https://github.com/jcabi/jcabi-github/issues/1403) was registered successfully by @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
The job [#1403](https://github.com/jcabi/jcabi-github/issues/1403) is now out of scope
