### ISSUE TITLE
RtRepo.java:187-189: Need to instantiate this...

### ISSUE THREAD

**Issue by 0pdd** [jcabi/jcabi-github#1406]
The puzzle `1400-f2b1cfe2` from #1400 has to be resolved:

https://github.com/jcabi/jcabi-github/blob/c6b49d93ca55fe54ddf73f881ef7bb033135aa62/src/main/java/com/jcabi/github/RtRepo.java#L187-L189

The puzzle was created by George Aristy on 06-May-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
@0pdd[/z](https://www.0crat.com/u/0pdd) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C9R53K5JA) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job [#1406](https://github.com/jcabi/jcabi-github/issues/1406) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1406](https://github.com/jcabi/jcabi-github/issues/1406) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/C9R53K5JA/1342026514); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
> @0crat waiting for review/merge of #1415  ([here](https://github.com/jcabi/jcabi-github/issues/1406#issuecomment-391372460))

@llorllale The impediment for [#1406](https://github.com/jcabi/jcabi-github/issues/1406) was registered successfully by @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0pdd** [comment]
The puzzle `1400-f2b1cfe2` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
The job [#1406](https://github.com/jcabi/jcabi-github/issues/1406) is now out of scope
