### ISSUE TITLE
Github Enterprise Support?

### ISSUE THREAD

**Issue by tarunngc** [jcabi/jcabi-github#1413]
Does this library have the ability to support enterprise hosted GitHub and its api?

Looking at the code briefly it seems that the public GitHub URL is hard coded in RtGithub.java

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
@tarunngc[/z](https://www.0crat.com/u/tarunngc) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C9R53K5JA) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by amihaiemil** [comment]
@tarunngc If Github Enterprise offers the same API as the normal Github then yes, you should be able to use it.

``RtGithub`` has a ctor where you can pass a ``Request``, see [here](https://github.com/jcabi/jcabi-github/blob/04e0bb106c2b183e971f23fc046027e1898a60ba/src/main/java/com/jcabi/github/RtGithub.java#L147). Just study ``RtGithub``'s constructors to see how to build that jcabi-http Request :)

**Comment by amihaiemil** [comment]
@tarunngc closing this as there are no developments -- please reopen if something reappears :)

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-github#1413` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
