### ISSUE TITLE
MkPull should return json with json patches

### ISSUE THREAD

**Issue by krzyk** [jcabi/jcabi-github#1424]
MkPull doesn't incorporate json patch into the result of `json()` method.

Example failing test, that should pass:
```
  Github github = new MkGithub();
  Repo repo = github.repos().create(new Repos.RepoCreate('test', false))
  Pull pull = repo.pulls().create('PR for hello, world', 'fixes', 'master')
  final int lines = 20;
  pull.patch(Json.createObjectBuilder().add('additions', lines).build())
  int lines = 
  MatcherAssert.assertThat(
    pull.json().getInt('additions', 0),
    Matchers.is(lines)
);
```

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C9R53K5JA) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by amihaiemil** [comment]
@krzyk looks like a bug. Care to contribute with a PR? There is only me and one DEV on this project (which has no funds), so I doubt we'll be able to fix it soon : D

**Comment by krzyk** [comment]
@amihaiemil I'll try :)

**Comment by amihaiemil** [comment]
@0crat assign @krzyk

**Comment by amihaiemil** [comment]
@krzyk you should at least get rep points, I think

**Comment by 0crat** [comment]
Job [#1424](https://github.com/jcabi/jcabi-github/issues/1424) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
> @0crat assign @krzyk  ([here](https://github.com/jcabi/jcabi-github/issues/1424#issuecomment-403425919))

@amihaiemil The job [#1424](https://github.com/jcabi/jcabi-github/issues/1424) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C9R53K5JA/1900974068); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @krzyk[/z](https://www.0crat.com/u/krzyk) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @krzyk[/z](https://www.0crat.com/u/krzyk) resigned from [#1424](https://github.com/jcabi/jcabi-github/issues/1424), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
The job [#1424](https://github.com/jcabi/jcabi-github/issues/1424) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/C9R53K5JA/2041019468); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by llorllale** [comment]
@amihaiemil the problem is inside `MkPull.json()`. It looks for specific xpaths - including the patches - to include in the JSON object. Right now, unless the user applies a patch with the key `"patch"`, then it won't be picked up by the implementation.

Any idea why this is? What should be the proper behavior? 

Btw, this was introduced all the way back in PR #1125 (note this foreboding comment!: https://github.com/jcabi/jcabi-github/pull/1125#discussion_r32560891).

**Comment by llorllale** [comment]
@0crat waiting for feedback [here](https://github.com/jcabi/jcabi-github/issues/1424#issuecomment-409313715)

**Comment by 0crat** [comment]
> @0crat waiting for feedback [here](https://github.com/jcabi/jcabi-github/issues/1424#issuecomment... ([here](https://github.com/jcabi/jcabi-github/issues/1424#issuecomment-409313806))

@llorllale The impediment for [#1424](https://github.com/jcabi/jcabi-github/issues/1424) was registered successfully by @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by llorllale** [comment]
@amihaiemil ping

**Comment by amihaiemil** [comment]
@llorllale I am on holiday, with a questionable sobriety, for 2 more weeks. Will have a look afterwards :)

**Comment by amihaiemil** [comment]
@llorllale I'm back. 

Well, I think either we leave it like this and user is obliged to use the hardcoded key when patching, or we change the implementation of ``MkPull.json()`` to parse the ``Pull`` xml ([this one](https://github.com/jcabi/jcabi-github/blob/master/src/main/java/com/jcabi/github/mock/MkPull.java#L211) into a JsonObject somehow.

**Comment by amihaiemil** [comment]
@0crat assign @paulodamaso

**Comment by 0crat** [comment]
> @0crat assign @paulodamaso  ([here](https://github.com/jcabi/jcabi-github/issues/1424#issuecomment-417567163))

@amihaiemil The job [#1424](https://github.com/jcabi/jcabi-github/issues/1424) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C9R53K5JA/2430640155); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by paulodamaso** [comment]
@amihaiemil Well, how about returning to the previous implementation (mentioned by @llorllale in https://github.com/jcabi/jcabi-github/pull/1125#discussion_r32560891)? The tests are passing because they have an error too (it'll always pass if we check for a `patch` attribute). WDYT?

**Comment by paulodamaso** [comment]
@amihaiemil Found a better solution, will merge the previous implementation with the actual allowing we to add any kind of items, without adding a `patch` item because it does not makes sense.

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@krzyk Merged, please close

**Comment by krzyk** [comment]
@paulodamaso thanks

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
The job [#1424](https://github.com/jcabi/jcabi-github/issues/1424) is now out of scope
