### ISSUE TITLE
Finish implementation of MkHook

### ISSUE THREAD

**Issue by paulodamaso** [jcabi/jcabi-github#1425]
`MkHook` does not implement all `Hook` interface methods; it throws an `UnsupportedOperationException` when the method `json() ` is called. Please implement this method accordingly and cover `MkHook` with tests.

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C9R53K5JA) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by amihaiemil** [comment]
@paulodamaso thanks for reporting. Interested in contributing with a PR? It's just me, the ARC, and one other DEV on this project which, unfortunately, is not funded :(

**Comment by 0crat** [comment]
Job [#1425](https://github.com/jcabi/jcabi-github/issues/1425) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1425](https://github.com/jcabi/jcabi-github/issues/1425) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C9R53K5JA/2340648201); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-github#1425` already assigned to @paulodamaso, can't assign to @paulodamaso

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by amihaiemil** [comment]
@paulodamaso feel free to put this task on hold until the CR replies

**Comment by 0pdd** [comment]
@paulodamaso the puzzle [#1430](https://github.com/jcabi/jcabi-github/issues/1430) is still not solved.

**Comment by paulodamaso** [comment]
@0crat status

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
The job [#1425](https://github.com/jcabi/jcabi-github/issues/1425) is now out of scope

**Comment by 0pdd** [comment]
@paulodamaso the puzzle [#1435](https://github.com/jcabi/jcabi-github/issues/1435) is still not solved; solved: [#1430](https://github.com/jcabi/jcabi-github/issues/1430).

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/jcabi/jcabi-github/issues/1425#issuecomment-416942990))

@paulodamaso This is what I know about this job in [C9R53K5JA](https://www.0crat.com/p/C9R53K5JA), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1425](https://github.com/jcabi/jcabi-github/issues/1425) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/C9R53K5JA?q=%7Bjob%3A%27gh%3Ajcabi%2Fjcabi-github%231425%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0pdd** [comment]
@paulodamaso the puzzle [#1439](https://github.com/jcabi/jcabi-github/issues/1439) is still not solved; solved: [#1430](https://github.com/jcabi/jcabi-github/issues/1430), [#1435](https://github.com/jcabi/jcabi-github/issues/1435).

**Comment by 0pdd** [comment]
@paulodamaso the puzzle [#1442](https://github.com/jcabi/jcabi-github/issues/1442) is still not solved; solved: [#1430](https://github.com/jcabi/jcabi-github/issues/1430), [#1435](https://github.com/jcabi/jcabi-github/issues/1435), [#1439](https://github.com/jcabi/jcabi-github/issues/1439).

**Comment by 0pdd** [comment]
@paulodamaso the puzzle [#1447](https://github.com/jcabi/jcabi-github/issues/1447) is still not solved; solved: [#1430](https://github.com/jcabi/jcabi-github/issues/1430), [#1435](https://github.com/jcabi/jcabi-github/issues/1435), [#1439](https://github.com/jcabi/jcabi-github/issues/1439), [#1442](https://github.com/jcabi/jcabi-github/issues/1442).

**Comment by 0pdd** [comment]
@paulodamaso all 5 puzzles are solved here: [#1430](https://github.com/jcabi/jcabi-github/issues/1430), [#1435](https://github.com/jcabi/jcabi-github/issues/1435), [#1439](https://github.com/jcabi/jcabi-github/issues/1439), [#1442](https://github.com/jcabi/jcabi-github/issues/1442), [#1447](https://github.com/jcabi/jcabi-github/issues/1447).
