### ISSUE TITLE
Outdated copyright info

### ISSUE THREAD

**Issue by paulodamaso** [jcabi/jcabi-github#1429]
A lot of files have outdated copyright info:
```
 * Copyright (c) 2013-2017, jcabi.com
 * All rights reserved.
```
We should correct this to 2018.

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by amihaiemil** [comment]
@paulodamaso If you want to fix it, I will assign it to you. Of course, use grep/sed, don't manually edit all of them :D

**Comment by 0crat** [comment]
Job [#1429](https://github.com/jcabi/jcabi-github/issues/1429) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by paulodamaso** [comment]
@0crat wait for #1431 review

**Comment by 0crat** [comment]
> @0crat wait for #1431 review ([here](https://github.com/jcabi/jcabi-github/issues/1429#issuecomment-417542158))

@paulodamaso The impediment for [#1429](https://github.com/jcabi/jcabi-github/issues/1429) was registered successfully by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by paulodamaso** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/jcabi/jcabi-github/issues/1429#issuecomment-417644786))

@paulodamaso GitHub issue is still open, won't close

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@3a1b338b-e779-4ac9-9f08-d687c3dfd092, thread: AsyncProc-3
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:jcabi/jcabi-github#1429] declared for identity constraint of element "verbosity".
```

[0.32.1](https://github.com/zerocracy/farm): CID: [2431217221](https://www.0crat.com/C9R53K5JA/2431217221), Type: "Close job", Author: "paulodamaso"

**Comment by 0crat** [comment]
Job was finished in 47 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by paulodamaso** [comment]
@amihaiemil Looks like something went wrong, please take a look.

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
The job [#1429](https://github.com/jcabi/jcabi-github/issues/1429) is now out of scope
