### ISSUE TITLE
MkHook.java:48-49: Finish adding tests for MkHook#json()....

### ISSUE THREAD

**Issue by 0pdd** [jcabi/jcabi-github#1435]
The puzzle `1425-9f6b6bf1` from #1425 has to be resolved:

https://github.com/jcabi/jcabi-github/blob/5ce8049134676db4a7781f86eaf585bdb89556b0/src/main/java/com/jcabi/github/mock/MkHook.java#L48-L49

The puzzle was created by George Aristy on 18-Sep-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1435](https://github.com/jcabi/jcabi-github/issues/1435) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1435](https://github.com/jcabi/jcabi-github/issues/1435) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/C9R53K5JA/2620669812); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by llorllale** [comment]
@0crat wait because I submitted PR #1437 for this

**Comment by 0pdd** [comment]
The puzzle `1425-9f6b6bf1` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1439](https://github.com/jcabi/jcabi-github/issues/1439) is still not solved.

**Comment by 0crat** [comment]
The job [#1435](https://github.com/jcabi/jcabi-github/issues/1435) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1442](https://github.com/jcabi/jcabi-github/issues/1442) is still not solved; solved: [#1439](https://github.com/jcabi/jcabi-github/issues/1439).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1447](https://github.com/jcabi/jcabi-github/issues/1447) is still not solved; solved: [#1439](https://github.com/jcabi/jcabi-github/issues/1439), [#1442](https://github.com/jcabi/jcabi-github/issues/1442).

**Comment by 0pdd** [comment]
@0pdd all 3 puzzles are solved here: [#1439](https://github.com/jcabi/jcabi-github/issues/1439), [#1442](https://github.com/jcabi/jcabi-github/issues/1442), [#1447](https://github.com/jcabi/jcabi-github/issues/1447).
