### ISSUE TITLE
Upgrade to Java 1.8

### ISSUE THREAD

**Issue by llorllale** [jcabi/jcabi-github#1438]
I've had to write verbose code for this project that would otherwise be unnecessary if we upgraded to Java 1.8 or later.

Let's please do the upgrade.

Edit: btw, the current build configuration is inconsistent with https://github.jcabi.com:

> Java 7 or higher is required.

Because when I try to use 1.8 features - such as lambdas - the build fails with:

> Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project jcabi-github: Compilation failure
[ERROR] /home/llorllale/dev/jcabi-github/src/main/java/com/jcabi/github/RtHooks.java:[136,26] lambda expressions are not supported in -source 1.6
[ERROR]   (use -source 8 or higher to enable lambda expressions)

Notice it says source level is 1.6, not 1.7.

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by amihaiemil** [comment]
@g4s8 Do you think it would be an issue for ``/farm`` if we updated jcabi-github to Java 8?

**Comment by g4s8** [comment]
@amihaiemil it should not, farm already uses 1.8

**Comment by amihaiemil** [comment]
@llorllale @paulodamaso Let's update it then.

**Comment by 0crat** [comment]
Job [#1438](https://github.com/jcabi/jcabi-github/issues/1438) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1438](https://github.com/jcabi/jcabi-github/issues/1438) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C9R53K5JA/2772145116); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@llorllale Merged, please close

**Comment by llorllale** [comment]
@paulodamaso thanks

@amihaiemil I feel like one big motivation for this was refactoring the code base, hence leaving a puzzle for continuing that work

**Comment by 0crat** [comment]
The job [#1438](https://github.com/jcabi/jcabi-github/issues/1438) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)
