### ISSUE TITLE
JsonNode.java:63-65: JsonNode should be smart enough to...

### ISSUE THREAD

**Issue by 0pdd** [jcabi/jcabi-github#1442]
The puzzle `1439-22936fd9` from #1439 has to be resolved: 

https://github.com/jcabi/jcabi-github/blob/d963d0eece204cae10c90b75cd247fb1fc3dda52/src/main/java/com/jcabi/github/mock/JsonNode.java#L63-L65

The puzzle was created by George Aristy on 18-Oct-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
Job [#1442](https://github.com/jcabi/jcabi-github/issues/1442) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1442](https://github.com/jcabi/jcabi-github/issues/1442) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C9R53K5JA/2911804408); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@0crat wait for https://github.com/jcabi/jcabi-github/pull/1444 review

**Comment by 0crat** [comment]
> @0crat wait for https://github.com/jcabi/jcabi-github/pull/1444 review ([here](https://github.com/jcabi/jcabi-github/issues/1442#issuecomment-433254920))

@paulodamaso The impediment for [#1442](https://github.com/jcabi/jcabi-github/issues/1442) was registered successfully by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0pdd** [comment]
The puzzle `1439-22936fd9` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
The job [#1442](https://github.com/jcabi/jcabi-github/issues/1442) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1447](https://github.com/jcabi/jcabi-github/issues/1447) is still not solved.

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#1447](https://github.com/jcabi/jcabi-github/issues/1447) is solved here.
