### ISSUE TITLE
Reaction.java:39-42: Implement Reactions to Comments and...

### ISSUE THREAD

**Issue by 0pdd** [jcabi/jcabi-github#1451]
The puzzle `1230-92aa948b` from #1230 has to be resolved: 

https://github.com/jcabi/jcabi-github/blob/c736f37bca18f14c94f7ac618fef88cfd3c5ab62/src/main/java/com/jcabi/github/Reaction.java#L39-L42

The puzzle was created by Paulo Lobo on 07-Dec-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1451](https://github.com/jcabi/jcabi-github/issues/1451) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1451](https://github.com/jcabi/jcabi-github/issues/1451) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C9R53K5JA/a6e9cb46-9d6f-4a75-be54-70dca88538e8); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0pdd** [comment]
The puzzle `1230-92aa948b` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil

**Comment by 0pdd** [comment]
@0pdd 5 puzzles [#1466](https://github.com/jcabi/jcabi-github/issues/1466), [#1467](https://github.com/jcabi/jcabi-github/issues/1467), [#1468](https://github.com/jcabi/jcabi-github/issues/1468), [#1469](https://github.com/jcabi/jcabi-github/issues/1469), [#1470](https://github.com/jcabi/jcabi-github/issues/1470) are still not solved.

**Comment by 0crat** [comment]
The job [#1451](https://github.com/jcabi/jcabi-github/issues/1451) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#1467](https://github.com/jcabi/jcabi-github/issues/1467), [#1468](https://github.com/jcabi/jcabi-github/issues/1468), [#1469](https://github.com/jcabi/jcabi-github/issues/1469), [#1470](https://github.com/jcabi/jcabi-github/issues/1470) are still not solved; solved: [#1466](https://github.com/jcabi/jcabi-github/issues/1466).

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#1467](https://github.com/jcabi/jcabi-github/issues/1467), [#1468](https://github.com/jcabi/jcabi-github/issues/1468), [#1470](https://github.com/jcabi/jcabi-github/issues/1470), [#1476](https://github.com/jcabi/jcabi-github/issues/1476) are still not solved; solved: [#1466](https://github.com/jcabi/jcabi-github/issues/1466), [#1469](https://github.com/jcabi/jcabi-github/issues/1469).

**Comment by 0pdd** [comment]
@0pdd 5 puzzles [#1467](https://github.com/jcabi/jcabi-github/issues/1467), [#1468](https://github.com/jcabi/jcabi-github/issues/1468), [#1470](https://github.com/jcabi/jcabi-github/issues/1470), [#1476](https://github.com/jcabi/jcabi-github/issues/1476), [#1477](https://github.com/jcabi/jcabi-github/issues/1477) are still not solved; solved: [#1466](https://github.com/jcabi/jcabi-github/issues/1466), [#1469](https://github.com/jcabi/jcabi-github/issues/1469).

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#1467](https://github.com/jcabi/jcabi-github/issues/1467), [#1470](https://github.com/jcabi/jcabi-github/issues/1470), [#1476](https://github.com/jcabi/jcabi-github/issues/1476), [#1477](https://github.com/jcabi/jcabi-github/issues/1477) are still not solved; solved: [#1466](https://github.com/jcabi/jcabi-github/issues/1466), [#1468](https://github.com/jcabi/jcabi-github/issues/1468), [#1469](https://github.com/jcabi/jcabi-github/issues/1469).

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#1470](https://github.com/jcabi/jcabi-github/issues/1470), [#1476](https://github.com/jcabi/jcabi-github/issues/1476), [#1477](https://github.com/jcabi/jcabi-github/issues/1477), [#1483](https://github.com/jcabi/jcabi-github/issues/1483) are still not solved; solved: [#1466](https://github.com/jcabi/jcabi-github/issues/1466), [#1467](https://github.com/jcabi/jcabi-github/issues/1467), [#1468](https://github.com/jcabi/jcabi-github/issues/1468), [#1469](https://github.com/jcabi/jcabi-github/issues/1469).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#1470](https://github.com/jcabi/jcabi-github/issues/1470), [#1476](https://github.com/jcabi/jcabi-github/issues/1476), [#1483](https://github.com/jcabi/jcabi-github/issues/1483) are still not solved; solved: [#1466](https://github.com/jcabi/jcabi-github/issues/1466), [#1467](https://github.com/jcabi/jcabi-github/issues/1467), [#1468](https://github.com/jcabi/jcabi-github/issues/1468), [#1469](https://github.com/jcabi/jcabi-github/issues/1469), [#1477](https://github.com/jcabi/jcabi-github/issues/1477).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#1476](https://github.com/jcabi/jcabi-github/issues/1476), [#1483](https://github.com/jcabi/jcabi-github/issues/1483) are still not solved; solved: [#1466](https://github.com/jcabi/jcabi-github/issues/1466), [#1467](https://github.com/jcabi/jcabi-github/issues/1467), [#1468](https://github.com/jcabi/jcabi-github/issues/1468), [#1469](https://github.com/jcabi/jcabi-github/issues/1469), [#1470](https://github.com/jcabi/jcabi-github/issues/1470), [#1477](https://github.com/jcabi/jcabi-github/issues/1477).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1476](https://github.com/jcabi/jcabi-github/issues/1476) is still not solved; solved: [#1466](https://github.com/jcabi/jcabi-github/issues/1466), [#1467](https://github.com/jcabi/jcabi-github/issues/1467), [#1468](https://github.com/jcabi/jcabi-github/issues/1468), [#1469](https://github.com/jcabi/jcabi-github/issues/1469), [#1470](https://github.com/jcabi/jcabi-github/issues/1470), [#1477](https://github.com/jcabi/jcabi-github/issues/1477), [#1483](https://github.com/jcabi/jcabi-github/issues/1483).
