### ISSUE TITLE
RtBranchesTest.java:114-117: Implement find method in...

### ISSUE THREAD

**Issue by 0pdd** [jcabi/jcabi-github#1457]
The puzzle `1086-abf60b5c` from #1086 has to be resolved: 

https://github.com/jcabi/jcabi-github/blob/859f2d36887de8fa95ecf6f7473857bd3c68f82a/src/test/java/com/jcabi/github/RtBranchesTest.java#L114-L117

The puzzle was created by Paulo Lobo on 18-Dec-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1457](https://github.com/jcabi/jcabi-github/issues/1457) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1457](https://github.com/jcabi/jcabi-github/issues/1457) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C9R53K5JA/3fff8b72-0209-4d63-8dc6-d6b41fe34db7); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by paulodamaso** [comment]
@0crat wait for #1458 review

**Comment by 0crat** [comment]
> @0crat wait for #1458 review ([here](https://github.com/jcabi/jcabi-github/issues/1457#issuecomment-449631211))

@paulodamaso The impediment for [#1457](https://github.com/jcabi/jcabi-github/issues/1457) was registered successfully by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0pdd** [comment]
The puzzle `1086-abf60b5c` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil

**Comment by 0crat** [comment]
The job [#1457](https://github.com/jcabi/jcabi-github/issues/1457) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)
