### ISSUE TITLE
Update website code snippet

### ISSUE THREAD

**Issue by amihaiemil** [jcabi/jcabi-github#1460]
On the project's [website](https://github.jcabi.com/) the example code-snippet will open an Issue in this repo, which is rather annoying. Let's change the snippet and make it point to the ``octocat/Hello-World`` repository (same as in the README).

The website is hosted on the ``gh-pages`` branch.

**Comment by 0crat** [comment]
Job [#1460](https://github.com/jcabi/jcabi-github/issues/1460) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
The job [#1460](https://github.com/jcabi/jcabi-github/issues/1460) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C9R53K5JA/3beb326e-d152-4eaa-8636-25ec4c33e346); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The job [#1460](https://github.com/jcabi/jcabi-github/issues/1460) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)
