### ISSUE TITLE
Issue.java:61-64: Implement Lock and unlock features to...

### ISSUE THREAD

**Issue by 0pdd** [jcabi/jcabi-github#1462]
The puzzle `1204-0dae0ae7` from #1204 has to be resolved: 

https://github.com/jcabi/jcabi-github/blob/cf87980922e40e0504d8cf55a9fd1596e8975283/src/main/java/com/jcabi/github/Issue.java#L61-L64

The puzzle was created by Paulo Lobo on 24-Dec-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
Job [#1462](https://github.com/jcabi/jcabi-github/issues/1462) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1462](https://github.com/jcabi/jcabi-github/issues/1462) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C9R53K5JA/1619aa56-47f5-4e40-b5e0-a0b1ed996d21); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0pdd** [comment]
The puzzle `1204-0dae0ae7` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1474](https://github.com/jcabi/jcabi-github/issues/1474) is still not solved.

**Comment by 0crat** [comment]
The job [#1462](https://github.com/jcabi/jcabi-github/issues/1462) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1558](https://github.com/jcabi/jcabi-github/issues/1558) is still not solved.

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#1474](https://github.com/jcabi/jcabi-github/issues/1474) is solved here.
