### ISSUE TITLE
Issue.java:65-67: Resume Reaction implementation on...

### ISSUE THREAD

**Issue by 0pdd** [jcabi/jcabi-github#1466]
The puzzle `1451-d6e99155` from #1451 has to be resolved: 

https://github.com/jcabi/jcabi-github/blob/55b5df5b2b06e314b135b4b83b4621614266e381/src/main/java/com/jcabi/github/Issue.java#L65-L67

The puzzle was created by rultor on 02-Jan-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1466](https://github.com/jcabi/jcabi-github/issues/1466) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0pdd** [comment]
The puzzle `1451-d6e99155` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil

**Comment by 0crat** [comment]
The job [#1466](https://github.com/jcabi/jcabi-github/issues/1466) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1477](https://github.com/jcabi/jcabi-github/issues/1477) is still not solved.

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#1477](https://github.com/jcabi/jcabi-github/issues/1477) is solved here.
