### ISSUE TITLE
Reaction.java:44-47: Create reaction values constants in...

### ISSUE THREAD

**Issue by 0pdd** [jcabi/jcabi-github#1468]
The puzzle `1451-68e7202f` from #1451 has to be resolved: 

https://github.com/jcabi/jcabi-github/blob/55b5df5b2b06e314b135b4b83b4621614266e381/src/main/java/com/jcabi/github/Reaction.java#L44-L47

The puzzle was created by rultor on 02-Jan-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1468](https://github.com/jcabi/jcabi-github/issues/1468) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1468](https://github.com/jcabi/jcabi-github/issues/1468) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C9R53K5JA/296c3814-e8e4-439c-bd77-f4c4b29b25c9); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-github#1468` already assigned to @paulodamaso, can't assign to @paulodamaso

**Comment by 0pdd** [comment]
The puzzle `1451-68e7202f` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil

**Comment by 0crat** [comment]
The job [#1468](https://github.com/jcabi/jcabi-github/issues/1468) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)
