### ISSUE TITLE
RtComment.java:48-50: Implement react ant reactions...

### ISSUE THREAD

**Issue by 0pdd** [jcabi/jcabi-github#1470]
The puzzle `1451-a700d53f` from #1451 has to be resolved: 

https://github.com/jcabi/jcabi-github/blob/55b5df5b2b06e314b135b4b83b4621614266e381/src/main/java/com/jcabi/github/RtComment.java#L48-L50

The puzzle was created by rultor on 02-Jan-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1470](https://github.com/jcabi/jcabi-github/issues/1470) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1470](https://github.com/jcabi/jcabi-github/issues/1470) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C9R53K5JA/71f9c2ec-0fe4-471e-895a-32432ed52e76); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-github#1470` already assigned to @paulodamaso, can't assign to @paulodamaso

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0pdd** [comment]
The puzzle `1451-a700d53f` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil

**Comment by 0crat** [comment]
The job [#1470](https://github.com/jcabi/jcabi-github/issues/1470) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)
