### ISSUE TITLE
RtIssue.java:50-52: Implement react and reactions...

### ISSUE THREAD

**Issue by 0pdd** [jcabi/jcabi-github#1477]
The puzzle `1466-fde76671` from #1466 has to be resolved: 

https://github.com/jcabi/jcabi-github/blob/4b33410a270691d2d6424e33d159e9b420f150ec/src/main/java/com/jcabi/github/RtIssue.java#L50-L52

The puzzle was created by @amihaiemil on 17-Jan-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1477](https://github.com/jcabi/jcabi-github/issues/1477) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1477](https://github.com/jcabi/jcabi-github/issues/1477) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C9R53K5JA/b92e6bc7-411f-4956-a930-6d52a7fa6a34); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `1466-fde76671` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil

**Comment by 0crat** [comment]
Job was finished in 44 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#1477](https://github.com/jcabi/jcabi-github/issues/1477) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)
