### ISSUE TITLE
Support setting API-endpoint

### ISSUE THREAD

**Issue by davidkarlsen** [jcabi/jcabi-github#1497]
https://github.com/jcabi/jcabi-github/blob/d3308efd6f3dac6017599d1b31a8f30664694c3b/src/main/java/com/jcabi/github/RtGithub.java seems to hard-code the api-endpoint.
Can you open this to be configurable? I'd like to use the SDK towards our enterprise instance.

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
@davidkarlsen[/z](https://www.0crat.com/u/davidkarlsen) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C9R53K5JA) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by davidkarlsen** [comment]
Relates to https://github.com/jcabi/jcabi-github/issues/871

**Comment by amihaiemil** [comment]
@davidkarlsen There is a public Constructor which accepts a ``Request`` object: https://github.com/jcabi/jcabi-github/blob/d3308efd6f3dac6017599d1b31a8f30664694c3b/src/main/java/com/jcabi/github/RtGithub.java#L147

Can you try to configure your own Request and use that Constructor? The Request is from the ``jcabi-http`` project, you can see how the static one is [configured](https://github.com/jcabi/jcabi-github/blob/d3308efd6f3dac6017599d1b31a8f30664694c3b/src/main/java/com/jcabi/github/RtGithub.java#L82) and try to do the same.

Did you maybe try already and had some problems?

**Comment by amihaiemil** [comment]
@davidkarlsen In principle, the Request should not be hard to configure: just choose between ApacheRequest and JdkRequest (whichever impl you want to have), add the base URI (and only that, the rest is fluently appended by the SDK as you call methods) + required HTTP Headers, like Authorization.

**Comment by davidkarlsen** [comment]
works like a charm - thanks!

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-github#1497` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
