### ISSUE TITLE
Error :java.lang.NoSuchFieldException: modifiers in jdk13 

### ISSUE THREAD

**Issue by rosetta-development** [jcabi/jcabi-github#1500]
When using JDK13 we got the following error: 

org.aspectj.lang.NoAspectBoundException: Exception while initializing com.jcabi.aspects.aj.MethodLogger: java.lang.IllegalStateException: **java.lang.NoSuchFieldException: modifiers**
        at com.jcabi.aspects.aj.MethodLogger.aspectOf(MethodLogger.java:1)
        at com.jcabi.github.RtGithub.repos(RtGithub.java:159)
        at 
----------------------------
Caused by: **java.lang.NoSuchFieldException: modifiers**
        at java.base/java.lang.Class.getDeclaredField(Class.java:2412)
        at com.jcabi.log.Logger.setFinalStatic(Logger.java:386)
        **at com.jcabi.log.Logger.logger(Logger.java:411)**
        ... 97 more

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
@rosetta-development[/z](https://www.0crat.com/u/rosetta-development) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C9R53K5JA) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by amihaiemil** [comment]
@rosetta-development This is actually an Issue with project jcabi-aspects. I've opened an Issue in that project. Let's move the discussion there.

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-github#1500` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
