### ISSUE TITLE
Fix Qulice errors and release #1502

### ISSUE THREAD

**Issue by amihaiemil** [jcabi/jcabi-github#1503]
PR #1502 has been merged, but it contains a few [Qulice errors](https://travis-ci.org/jcabi/jcabi-github/builds/637260143#L2082).
Let's fix them so we can release a new version.

**Comment by 0crat** [comment]
The job [#1503](https://github.com/jcabi/jcabi-github/issues/1503) assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/C9R53K5JA/20a955b8-9029-4ca9-a101-b734de8df4c7); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-github#1503` already assigned to @amihaiemil, can't assign to @amihaiemil

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
The job [#1503](https://github.com/jcabi/jcabi-github/issues/1503) is now out of scope

**Comment by 0crat** [comment]
Job was finished in 9 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
