### ISSUE TITLE
Add tests for RepoCreate with Organization

### ISSUE THREAD

**Issue by amihaiemil** [jcabi/jcabi-github#1504]
From #1502 

Add a unit test and an integration test for creating a Repo under a organization (``Github.repos().create(...)``).

**Comment by amihaiemil** [comment]
@0crat assign @maviteixeira

**Comment by 0crat** [comment]
> @0crat assign @maviteixeira ([here](https://github.com/jcabi/jcabi-github/issues/1504#issuecomment-582655980))

@amihaiemil The job [#1504](https://github.com/jcabi/jcabi-github/issues/1504) assigned to @maviteixeira[/z](https://www.0crat.com/u/maviteixeira), here is [why](https://www.0crat.com/footprint/C9R53K5JA/5c0d4989-9c72-4976-a6e8-51024b3ff9fb); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @maviteixeira[/z](https://www.0crat.com/u/maviteixeira) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
@maviteixeira[/z](https://www.0crat.com/u/maviteixeira) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@maviteixeira[/z](https://www.0crat.com/u/maviteixeira) resigned from [#1504](https://github.com/jcabi/jcabi-github/issues/1504), since the job is not in scope anymore

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 11@706b9e63c3bc, thread: PQ-C9R53K5JA
com.zerocracy.claims.ClaimIn[214] java.lang.IllegalArgumentException: Parameter "age" not found in "Order was canceled" among: [reason, priority, job, cause, _parent_sig, flow, voluntarily, login]
```

[0.51.6](https://github.com/zerocracy/farm): CID: [7f818c15-4c02-4488-abd1-1435e33ec7ef](https://www.0crat.com/footprint/C9R53K5JA/7f818c15-4c02-4488-abd1-1435e33ec7ef), Type: "Order was canceled"
