### ISSUE TITLE
Implement the Mock version for RepoCreate with Org

### ISSUE THREAD

**Issue by amihaiemil** [jcabi/jcabi-github#1505]
From #1502 

We should also implement the mock version for creating a repo under an organization (``MkGithub.repos().create(...)``)

**Comment by amihaiemil** [comment]
@maviteixeira Do you also have the time/willingness to fix this issue? I've seen you understood how the mock version works :D

**Comment by 0crat** [comment]
Job [#1505](https://github.com/jcabi/jcabi-github/issues/1505) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by maviteixeira** [comment]
@amihaiemil Sure, no problem.
Could you please check the [PR ](https://github.com/jcabi/jcabi-github/pull/1519)and see if it is what you expected?

**Comment by amihaiemil** [comment]
@0crat assign @maviteixeira

**Comment by 0crat** [comment]
> @0crat assign @maviteixeira ([here](https://github.com/jcabi/jcabi-github/issues/1505#issuecomment-578511388))

@amihaiemil The job [#1505](https://github.com/jcabi/jcabi-github/issues/1505) assigned to @maviteixeira[/z](https://www.0crat.com/u/maviteixeira), here is [why](https://www.0crat.com/footprint/C9R53K5JA/70a794e8-f593-47f6-b5ff-ad17dac94eff); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @maviteixeira[/z](https://www.0crat.com/u/maviteixeira) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @maviteixeira[/z](https://www.0crat.com/u/maviteixeira), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Job was finished in 20 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#1505](https://github.com/jcabi/jcabi-github/issues/1505) is now out of scope

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +40 point(s) just awarded to @maviteixeira[/z](https://www.0crat.com/u/maviteixeira)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)
