### ISSUE TITLE
Release version 1.1

### ISSUE THREAD

**Issue by amihaiemil** [jcabi/jcabi-github#1507]
Let's release version 1.1

Changes:

- Implemented repo creation inside organizations (#1502);
- Implemented ``Repos.exists(...)`` (#1508  and #1512);
- Added constructors for class RtGithub, through which users can specify a different domain.  (#1518)

**Comment by amihaiemil** [comment]
@rultor release it, tag is `1.1`

**Comment by amihaiemil** [comment]
@rultor release it, tag is `1.1`

**Comment by amihaiemil** [comment]
@ShalomGottesman The rultor chatbot is having some problems (see [here](https://github.com/yegor256/rultor/issues/1324)). 

We have to wait until it is fixed, so we can release to Maven Central.

I cannot release it manually because I don't have the required credentials and GPG keys... it is all automated by rultor.

**Comment by amihaiemil** [comment]
@rultor release it, tag is `1.1`

**Comment by amihaiemil** [comment]
@rultor release it, tag is `1.1`

**Comment by amihaiemil** [comment]
@rultor release it, tag is `1.1`

**Comment by amihaiemil** [comment]
@rultor release it, tag is `1.1`

**Comment by amihaiemil** [comment]
@ShalomGottesman We still have problems with rultor. I'm trying to fix it now.

**Comment by amihaiemil** [comment]
@rultor release it, tag is `1.1`

**Comment by amihaiemil** [comment]
@rultor release it, tag is `1.1`

**Comment by amihaiemil** [comment]
@rultor release it, tag is `1.1`

**Comment by amihaiemil** [comment]
@rultor release it, tag is `1.1`

**Comment by amihaiemil** [comment]
@rultor release it, tag is `1.1`

**Comment by amihaiemil** [comment]
@yegor256 See here? Maven build cannot download deps because it still uses HTTP.

We need the new version of Maven which you added in the ``yegor256/rultor-image`` Dockerfile.

This repo uses ``yegor256/java8`` which still inherits from the old ``yegor256/rultor`` -- that's why we need to rebuild it on DockerHub...

**Comment by amihaiemil** [comment]
@rultor try to release tag is `1.1`

**Comment by amihaiemil** [comment]
@rultor release it, tag is `1.1`

**Comment by amihaiemil** [comment]
@rultor release it, tag is `1.1`

**Comment by amihaiemil** [comment]
@rultor release it, tag is `1.1`

**Comment by amihaiemil** [comment]
@rultor try to release, tag is `1.1`

**Comment by ShalomGottesman** [comment]
Has this been looked into?

**Comment by amihaiemil** [comment]
@ShalomGottesman FYI, version 1.1 is now released.

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-github#1507` is not assigned, can't get performer
