### ISSUE TITLE
Fix checkstyle for PR 1508

### ISSUE THREAD

**Issue by amihaiemil** [jcabi/jcabi-github#1509]
Fix checkstyle errors for PR #1508. See [here](https://travis-ci.org/jcabi/jcabi-github/builds/639027560#L2082)

**Comment by amihaiemil** [comment]
@ShalomGottesman I will fix the checkstyle errors and I will also rename your method from ``contains`` to ``exists`` :)

**Comment by 0crat** [comment]
Job [#1509](https://github.com/jcabi/jcabi-github/issues/1509) is closed, can't start order

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-github#1509` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
