### ISSUE TITLE
Add tests for RtRepos.exists(...)

### ISSUE THREAD

**Issue by amihaiemil** [jcabi/jcabi-github#1510]
We should add unit and integration tests for method RtRepos.exists(...);

**Comment by constantinosloizou** [comment]
What is this method suppose to do?

**Comment by amihaiemil** [comment]
@constantinosloizou This method checks if the given repository (Coordinates) exists on Github or not. 

If you want to contribute, you can start with a unit test. Have a look and see how other unit tests are done. In principle, you start a **mock** HTTP Server, define a port, make the Request and the query the mock HTTP Endpoint to see how the Request that got to it looks like -- obviously, the request should be the one that is constructed inside ``RtRepos.exists(...)``.

**Comment by amihaiemil** [comment]
@0crat assign @maviteixeira

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
> @0crat assign @maviteixeira  ([here](https://github.com/jcabi/jcabi-github/issues/1510#issuecomment-582017352))

@amihaiemil The job [#1510](https://github.com/jcabi/jcabi-github/issues/1510) assigned to @maviteixeira[/z](https://www.0crat.com/u/maviteixeira), here is [why](https://www.0crat.com/footprint/C9R53K5JA/6b6c6a77-0a61-457d-af16-def787b2ee1e); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @maviteixeira[/z](https://www.0crat.com/u/maviteixeira) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @maviteixeira[/z](https://www.0crat.com/u/maviteixeira), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@constantinosloizou please make sure you start all the comments with the name of the user they are referred to, [see](https://github.com/jcabi/jcabi-github/issues/1510#issuecomment-576020800)

**Comment by amihaiemil** [comment]
@sereshqua I fixed that comment. Please give a 'good' verdict, that person is not part of our team.

**Comment by sereshqua** [comment]
@amihaiemil i am sorry, but the policy is the same, if there is smb who did not keep - it is rule violation; i will need to wait his comment that he would not do in next issues

**Comment by amihaiemil** [comment]
@sereshqua this is an opensource project with no budget. Please do as I asked and let's move on with our lives.

I personally find this QA layer quite useless...

**Comment by amihaiemil** [comment]
@sereshqua that person will probably never reply, I'm talking from experience.

Give a good verdict please and let's move on.

**Comment by sereshqua** [comment]
@amihaiemil sorry, but policy is policy, I disagree

**Comment by sereshqua** [comment]
@amihaiemil 

if this person does reply within 4 days, then I would give a verdict 

> @sereshqua that person will probably never reply, I'm talking from experience.
> 
> Give a good verdict please and let's move on.

**Comment by sereshqua** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +35 point(s) just awarded to @maviteixeira[/z](https://www.0crat.com/u/maviteixeira)
