### ISSUE TITLE
Organization github

### ISSUE THREAD

**Issue by kkashi01** [jcabi/jcabi-github#1516]
This is great tool. However, We have github that has been setup for our organization (github.xxxx.com). Is there anyway to change the base url to use url other than github.com?

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
@kkashi01[/z](https://www.0crat.com/u/kkashi01) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C9R53K5JA) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by amihaiemil** [comment]
@kkashi01 Yes, there is the constructor [RtGithub(Request)](https://github.com/jcabi/jcabi-github/blob/master/src/main/java/com/jcabi/github/RtGithub.java#L147). 

You can configure your own request with your URL. However, you have to also configure the Content-Type and other headers. See how the [default Request](https://github.com/jcabi/jcabi-github/blob/master/src/main/java/com/jcabi/github/RtGithub.java#L82) is configured. 

Also see how the ``token`` or ``auth`` headers are added to it: https://github.com/jcabi/jcabi-github/blob/master/src/main/java/com/jcabi/github/RtGithub.java#L111

**Comment by amihaiemil** [comment]
@kkashi01 I added the explanation in the README: https://github.com/jcabi/jcabi-github#work-with-githubs-api

**Comment by amihaiemil** [comment]
@kkashi01 I'm closing this ticket. Feel free to open another one if you encounter any other issues.

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-github#1516` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
