### ISSUE TITLE
Add collaborator to organization repo with permissions

### ISSUE THREAD

**Issue by ShalomGottesman** [jcabi/jcabi-github#1521]
Does the Request object have the ability to add parameters? For purposes like this:
https://developer.github.com/v3/repos/collaborators/#add-user-as-a-collaborator

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
@shalomgottesman[/z](https://www.0crat.com/u/shalomgottesman) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C9R53K5JA) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by amihaiemil** [comment]
@ShalomGottesman Yes, you should be able to do it via the ``uri()`` method (which returns the ``RequestURI``: 

```java
Request req = req.uri().queryParam("permission", "pull").back();
```

**Comment by ShalomGottesman** [comment]
@amihaiemil Will this work with also editing the path and when using a Request.PUT method?

**Comment by amihaiemil** [comment]
@ShalomGottesman I don't see any reason why it shouldn't work. Give it a try and open a ticket is something goes wrong :)

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-github#1521` is not assigned, can't get performer
