### ISSUE TITLE
Add collaborator with permission not working

### ISSUE THREAD

**Issue by ShalomGottesman** [jcabi/jcabi-github#1529]
I am trying to add a collaborator to an organization repository with the following code:

Github github = new RtGithub("ShalomGottesman", "*************");
		JsonResponse body = github.entry().uri()
				.queryParam("permission",  "pull")
				.path("/repos/OWNER/REPO/collaborators/PERSON_TO_ADD")
				.back().method(Request.PUT).body().back().fetch().as(JsonResponse.class);
Where OWNER, REPO, and PERSON_TO_ADD are filled in with a real organization, real repository and real GitHub handle.
However on the GitHub UI the invitation reads as permission to push as well. Am I missing a parameter that has to be added? According to the GitHub api documents the "permission" is all that is needed. https://developer.github.com/v3/repos/collaborators/#add-user-as-a-collaborator

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by amihaiemil** [comment]
@ShalomGottesman To be honest, I have no idea, sorry. 

But your code is correct and this question has nothing to do with jcabi-github, but rather with Github's API itself. Therefore, I am closing this ticket.

I suggest you ask this question on StackOverflow and/or reddit/r/github. Maybe if you write an e-mail to Github's Support, they could help.

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-github#1529` is not assigned, can't get performer
