### ISSUE TITLE
Commit.Smart#isVerified()

### ISSUE THREAD

**Issue by yegor256** [jcabi/jcabi-github#1530]
Let's implement `isVerified()` method

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#1530](https://github.com/jcabi/jcabi-github/issues/1530) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C9R53K5JA/9cf981d2-5206-4ceb-af73-5d06983f38dc); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by yegor256** [comment]
@rultor release, tag is `1.1`

**Comment by yegor256** [comment]
@rultor release, tag is `1.1`

**Comment by yegor256** [comment]
@rultor release, tag is `1.1`

**Comment by yegor256** [comment]
@rultor stop

**Comment by yegor256** [comment]
@rultor release, tag is `1.1`

**Comment by 0crat** [comment]
Job was finished in 9 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
