### ISSUE TITLE
Adding collaborator asserts wrong return code

### ISSUE THREAD

**Issue by ShalomGottesman** [jcabi/jcabi-github#1533]
RtCollaborator.add asserts the return value to HttpURLConnection.HTTP_NO_CONTENT
As per https://developer.github.com/v3/repos/collaborators/#response-when-person-is-already-a-collaborator, the 204 return is only if the user is ALREADY a collaborator, but when adding a new one should be 201 (HttpURLConnection.HTTP_CREATED). See https://developer.github.com/v3/repos/collaborators/#response-when-a-new-invitation-is-created

Can this be changed?

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by amihaiemil** [comment]
@ShalomGottesman Yes, it can be changed, 2 or more stati can be specified. You can look at the isCollaborator method from the same class, to see how.

Please, make a Pull Request, there is nobody working on this at the moment.

**Comment by amihaiemil** [comment]
released with 1.1.2

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-github#1533` is not assigned, can't get performer
