### ISSUE TITLE
Release 1.1.2

### ISSUE THREAD

**Issue by amihaiemil** [jcabi/jcabi-github#1535]
Let's release 1.1.2, it contains: #1532 and #1534

**Comment by amihaiemil** [comment]
@rultor release it, tag is `1.1.2`

**Comment by amihaiemil** [comment]
@ShalomGottesman Version ``1.1.2`` with your 2 PRs has just been released, thanks!

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-github#1535` is not assigned, can't get performer
