### ISSUE TITLE
https://github.jcabi.com/ is out of date

### ISSUE THREAD

**Issue by andreoss** [jcabi/jcabi-github#1539]
[The site](https://github.jcabi.com/) is displaying information about 0.41
Probably related to https://github.com/jcabi/jcabi-http/issues/203

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by amihaiemil** [comment]
@andreoss Can you please investigate and make a Pull Request? The website is generated by Maven, but I'm not sure of the details. :)

**Comment by andreoss** [comment]
@amihaiemil 
`site` profile was fixed by this PR https://github.com/jcabi/jcabi-parent/pull/96
We need to switch to a newer parent (https://github.com/jcabi/jcabi/pull/324), and run `@rultor deploy`.
Note that rultor will ignore site deployment failures:
https://github.com/jcabi/jcabi-github/blob/master/.rultor.yml#L27

**Comment by andreoss** [comment]
@amihaiemil  
The root cause is https://github.com/jcabi/jcabi-maven-skin/issues/34.
The work-around would be to remove `<head>` from `site.xml`

**Comment by amihaiemil** [comment]
@andreoss that's quite an important part of an HTML page. Maybe you can make a PR to fix ths issue in jcabi-maven-skin?

**Comment by andreoss** [comment]
@amihaiemil Please take a look at https://github.com/jcabi/jcabi-maven-skin/pull/37.

Can you also elaborate please on why it's important to have this macro?

**Comment by amihaiemil** [comment]
@andreoss I have no idea what that macro is or what is it for, sorry :)

**Comment by yegor256** [comment]
@andreoss fixed
