### ISSUE TITLE
Support Github Apps API

### ISSUE THREAD

**Issue by Haarolean** [jcabi/jcabi-github#1635]
Hi,

there seems to be no support for Github App's API.

Docs could be found [here](https://docs.github.com/en/rest/apps/apps?apiVersion=2022-11-28#list-installation-requests-for-the-authenticated-app).

[The other](https://github-api.kohsuke.org/) existing GH API library does support this, I guess it could be useful to take a look, if someone will be interested in implementing this whenever.

Cheers.

**Comment by yegor256** [comment]
@Haarolean you are welcome to implement it and submit pull requests to us!
