### ISSUE TITLE
User.java:93-98: Implement methods to retrieve all...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-github#825]
Puzzle `1-294610ab` in `src/main/java/com/jcabi/github/User.java:93-98` has to be resolved: Implement methods to retrieve all values provided by Github for a single user, see: http://developer.github.com/v3/users/#get-a-single-user At the moment we implement just a few, but every data items should have its own method. Of course, every new item should be tested by a new unit test method.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by yegor256** [comment]
@cyberone the problem is that you didn't remove the original puzzle from the source code. That's why the task is still open. Please remove it in a new pull request.

**Comment by cyberone** [comment]
@yegor256 @dmarkov removed puzzle, see https://github.com/jcabi/jcabi-github/pull/983

**Comment by cyberone** [comment]
@dmarkov the PR is merged, close the task please.

**Comment by dmarkov** [comment]
The task is done, thanks all, I'm closing it

**Comment by dmarkov** [comment]
@cyberone done, I added **30 mins** in payment `50570740`. +30 added to your rating, at the moment it is: [-670](http://www.netbout.com/b/35076?open=rating)

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@rultor deploy
