### ISSUE TITLE
Does jcabi-github support enterprise?

### ISSUE THREAD

**Issue by cynosureabu** [jcabi/jcabi-github#871]
I simply need to read a file content from a repo..

**Comment by EdwardTang** [comment]
I am wondering how to get a file content from enterprise URI like https://api.github.cerner.com. I looked into the RtGithub class and found the default API URI is hard coded as following:
```
private static final Request REQUEST =
        new ApacheRequest("https://api.github.com")
            .header(HttpHeaders.USER_AGENT, RtGithub.USER_AGENT)
            .header(HttpHeaders.ACCEPT, MediaType.APPLICATION_JSON)
            .header(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_JSON);
```
Is there a way to customized the default API URI?  I simply just need read the file content anoymously from enterprise Github repos.

**Comment by rdifrango** [comment]
I had the same question as we have an enterprise instances of GitHub, thus we need to customize the URI that's container in the `REQUEST` object.
