### ISSUE TITLE
Stars.java:41-43: Implement missing starring operations. At...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-github#919]
Puzzle `907-c7787adc` in `src/main/java/com/jcabi/github/Stars.java:41-43` has to be resolved: Implement missing starring operations. At least star, unstar and starred operations should be implemented in RtStars and MkStars. Don't forget about unit and integrations tests.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by yegor256** [comment]
@rultor release, tag is `0.18.3`

**Comment by dmarkov** [comment]
last 5 puzzles `919-44e20d78`/#948, `919-68f3d556`/#949, `919-ca1c0738`/#950, `950-4b919e8a`/#965, `919-008dea91`/#956 originated from here were solved
