### ISSUE TITLE
Adding comments to pull requests

### ISSUE THREAD

**Issue by zygm0nt** [jcabi/jcabi-github#927]
Hi

I'm having trouble adding comments to pull request contents.

```
Pull p = repo.pulls().get(2);
p.comments().post("Comment 1",
                    "sha",
                    "file path", 27);
```

I'm trying to add comment to line 27, which is actually the line in the diff. 

But what I'd also like to do is add comments to other lines and add comments to pull request, without associating a specific line.

Trying to execute the above code results in 404 error from Github, which I don't understand, cause I have a PR number 2 with a given file in it.

What am I doing wrong?

**Comment by yegor256** [comment]
@dmarkov please close this issue. @zygm0nt feel free to submit a new one if you have a similar problem (or any other)

**Comment by dmarkov** [comment]
> @dmarkov please close this issue. @zygm0nt feel free to submit a new one if you have a similar problem (or any other)

@yegor256 issue closes as you just asked

**Comment by dmarkov** [comment]
@yegor256 Thanks so much! Your account was topped up for **30 mins** (transaction ID is `000-646434bd`)

+30 added to your rating, current score is: [+4460](http://www.netbout.com/b/35008?open=rating)
