### ISSUE TITLE
MkMilestone is not implemented

### ISSUE THREAD

**Issue by yegor256** [jcabi/jcabi-github#938]
Methods in `MkMilestone` are not implemented. Let's fix that.

**Comment by yegor256** [comment]
@dmarkov please assign someone else

**Comment by dmarkov** [comment]
> @dmarkov please assign someone else

@yegor256 I'll ask somebody else to pick this up

**Comment by dmarkov** [comment]
@romankisilenko could you please pick this up? This [article](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) explains how we work. Any technical questions you may ask right here... Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by RomanKisilenko** [comment]
@yegor256 PR was reviewed and closed, please close this issue.

**Comment by yegor256** [comment]
@RomanKisilenko thanks!

**Comment by dmarkov** [comment]
@romankisilenko **30 mins** was added to your account, many thanks for your contribution!; +30 to your rating, your total score is +450
