### ISSUE TITLE
Not Human Problem

### ISSUE THREAD

**Issue by ghost** [jcabi/jcabi-github#940]
It always shows this message .....
(One of our mostly harmless robots seems to think you are not a human.)

please fix this problem

**Comment by erwinvaneyk** [comment]
You are probably using regular username/password authentication, right? Github blocks bot-like requests using method, which is meant for actual human-users. Use the [OAuth tokens](https://github.com/settings/applications) ;)

**Comment by dmarkov** [comment]
@yegor256 please do something about this issue

**Comment by reiz** [comment]
I was running into this issue as well. Have some selenium integration tests for [VersionEye](https://www.versioneye.com) which fail because of this. In my case it's even true because it's an automated integration test, but it's annoying anyway. How can we fix it?

**Comment by hhsadiq** [comment]
I also got this exact problem. They blocked my profile from public. I reported this problem at support and profile was restored in less than half an hour. I think github guys have programmed their NOT SO HARMLESS robot with some weird too-strict rules. They definitely need to revise their policy, it is giving too many false positives.

**Comment by reiz** [comment]
I'm still getting it from time to time :-|
