### ISSUE TITLE
RtRepoCommit uses wrong request path

### ISSUE THREAD

**Issue by krzyk** [jcabi/jcabi-github#943]
`RtRepoCommit` is and implementation of `RepoCommit` which implements  http://developer.github.com/v3/repos/commits/. But the request it performs is not correct (according to the documentation mentioned):

`
GET /repos/jcabi/jcabi-github/git/commits/e877e28dc3870355d689021c46514ea7bc48714e 
`

It should perform following request (notice that `/git/` element does not appear below):
`
GET /repos/jcabi/jcabi-github/commits/e877e28dc3870355d689021c46514ea7bc48714e 
`

**Comment by dmarkov** [comment]
@cyberone **30 mins** added to your account (payment number `49702690`), many thanks for your contribution!
