### ISSUE TITLE
RtStarsITestCase.java:37-39: Implement integration tests for star(),...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-github#949]
Puzzle `919-68f3d556` in `src/test/java/com/jcabi/github/RtStarsITestCase.java:37-39` has to be resolved: Implement integration tests for star(), unstar() and starred() operations. See https://developer.github.com/v3/activity/starring/ for details.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by wentwog** [comment]
@dmarkov I'm currently working on this task. Hope to complete in the 10d deadline and hope you won't subtract points earlier ).

**Comment by wentwog** [comment]
@dmarkov I've created PR #966

**Comment by wentwog** [comment]
@dmarkov the PL was merged. Could you close the issue ?

**Comment by dmarkov** [comment]
Thanks, closed

**Comment by dmarkov** [comment]
@wentwog Much obliged! I've added **30 mins** to your account in payment "50300758". added +30 to your rating, now it is equal to [+50](http://www.netbout.com/b/35104?open=rating)
