### ISSUE TITLE
MkNotifications.java:45-46: Implement iterate() and get() operations...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-github#952]
Puzzle `920-82c5cb6b` in `src/main/java/com/jcabi/github/mock/MkNotifications.java:45-46` has to be resolved: Implement iterate() and get() operations in MkNotifications. Don't forget about unit tests.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by dmarkov** [comment]
@flexelem the task is overdue, and I have to re-assign it to someone else. Please, stop working with it immediately. In general, we're against overdue tasks, check [this page](http://www.xdsd.org/2014/04/13/no-obligations-principle.html)... added -60 to your rating, now it is equal to -185

**Comment by dmarkov** [comment]
@nathansgreen please proceed, it's yours

**Comment by nathansgreen** [comment]
@dmarkov please assign to someone else

**Comment by dmarkov** [comment]
> @dmarkov please assign to someone else

@nathansgreen no problem, I'll try to find somebody else

**Comment by dmarkov** [comment]
@prondzyn this task is yours, please help (see our key [principles of work](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html)). If you have any technical questions, don't hesitate to ask right here. Budget here is **30 mins** (keep [this principle](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind)

**Comment by prondzyn** [comment]
@dmarkov PR #1174 prepared

**Comment by dmarkov** [comment]
> @dmarkov PR #1174 prepared

@prondzyn thanks, will someone to review it soon

**Comment by prondzyn** [comment]
@dmarkov issue completed and merged

**Comment by dmarkov** [comment]
> @dmarkov issue completed and merged

@prondzyn thanks

**Comment by dmarkov** [comment]
@yegor256 Done, the task is closed

**Comment by dmarkov** [comment]
@prondzyn Much appreciated! **30 mins** was added to your account, payment ID `AP-1R597726YE984414W`, time spent is 362 hours and 45 mins

+30 to your rating, your total score is [+45](http://www.netbout.com/b/35715?open=rating)
