### ISSUE TITLE
MkRepo.java:68-69: Implement languages() method. Don't forget...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-github#953]
Puzzle `923-0c07ba46` in `src/main/java/com/jcabi/github/mock/MkRepo.java:68-69` has to be resolved: Implement languages() method. Don't forget about unit tests.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by AlexDag** [comment]
@dmarkov - I'm starting this job now.thanks

**Comment by dmarkov** [comment]
@alexdag you've been working with this task for too long. I'm sorry, but I'll assign someone else. Please stop working with it. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle. -60 added to your rating, current score is: [-120](http://www.netbout.com/b/35099?open=rating)

**Comment by dmarkov** [comment]
@nhekfqn can you please help? Keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If you have any technical questions, don't hesitate to ask right here

The budget of this issue is **30 mins**, which is exactly how much will be paid when the task is *done* (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by nhekfqn** [comment]
PR created https://github.com/jcabi/jcabi-github/pull/994

**Comment by nhekfqn** [comment]
@dmarkov PR updated.

**Comment by nhekfqn** [comment]
@dmarkov related pull request has been merged.

**Comment by nhekfqn** [comment]
@dmarkov can we close the ticket please?

**Comment by dmarkov** [comment]
Closing, thanks all

**Comment by dmarkov** [comment]
@nhekfqn Much appreciated! **30 mins** was added to your account, payment ID `50904297`. +30 added to your rating, current score is: [+45](http://www.netbout.com/b/35123?open=rating)
