### ISSUE TITLE
RtRepo.java:49-52: Let's implement RtRepo.languages(). Now it...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-github#954]
Puzzle `923-96eac598` in `src/main/java/com/jcabi/github/RtRepo.java:49-52` has to be resolved: Let's implement RtRepo.languages(). Now it returns empty iterable but should return list of repo languages. Uncomment test RtRepoTest.iteratesLanguages() when done. See https://developer.github.com/v3/repos/#list-languages for API details.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by dmarkov** [comment]
@nhekfqn this task is yours, please help (see our key [principles of work](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html)). If you have any technical questions, don't hesitate to ask right here

Total fixed cost of this task is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more info)

**Comment by nhekfqn** [comment]
Just in case: as discussed with Yegor, I'll start working on tasks at 5th of January.

**Comment by nhekfqn** [comment]
Pull request sent https://github.com/jcabi/jcabi-github/pull/959

Implemented using RtJson as there is no fancy thing like RtPagination to parse and map json object's fields. I believe implementing such utility (RtObjectPagination?) should be separate task.

**Comment by yegor256** [comment]
@nhekfqn don't hesitate to submit a ticket, if you think that such an improvement would be beneficial for the project

**Comment by nhekfqn** [comment]
Issue created https://github.com/jcabi/jcabi-github/issues/960

**Comment by nhekfqn** [comment]
@dmarkov should I notify that PR https://github.com/jcabi/jcabi-github/pull/978 has been merged?

**Comment by nhekfqn** [comment]
@dmarkov https://github.com/jcabi/jcabi-github/pull/978 has been merged. Can I get payment and we close the ticket now?

**Comment by dmarkov** [comment]
@nhekfqn the task is your hands for the last 13 days.. keep in mind that if it's not closed in the next 16 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle. do not forget that the ticket will be closed once the `@todo` puzzle is removed from the code, in master branch. added -30 to your rating, now it is equal to [-60](http://www.netbout.com/b/35123?open=rating)

**Comment by nhekfqn** [comment]
@dmarkov @todo puzzle has been removed from code, in master branch https://github.com/jcabi/jcabi-github/blob/master/src/main/java/com/jcabi/github/RtRepo.java Please close the ticket.

**Comment by nhekfqn** [comment]
@dmarkov Please close the ticket.

**Comment by dmarkov** [comment]
I'm closing it, thanks all

**Comment by dmarkov** [comment]
@nhekfqn Thanks a lot, I just topped your account for **30 mins**, transaction ID `50517706`. +30 to your rating, your total score is [+0](http://www.netbout.com/b/35123?open=rating)
