### ISSUE TITLE
RtRepoITCase.java:47-48: Add integration test on Repo.languages()....

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-github#955]
Puzzle `923-bb4ba39b` in `src/test/java/com/jcabi/github/RtRepoITCase.java:47-48` has to be resolved: Add integration test on Repo.languages(). See https://developer.github.com/v3/repos/#list-languages for API details

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by dmarkov** [comment]
@maxim-kornienko this ticket is yours now, please proceed, and keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions you should ask right here

**30 mins** is the budget of the task. This is exactly how much will be paid when the problem is [solved](http://www.xdsd.org/2014/04/15/definition-of-done.html) (no matter how much time you will actually spend). See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by maxim-kornienko** [comment]
@dmarkov Pull request is closed, may we close the issue now? 
I have general question: do I need to comment to issue when pull request is merged or it's redundant?

**Comment by yegor256** [comment]
@maxim-kornienko it's better to do it. Moreover, it's good to give the number of the pull request, where the issue is fixed.

**Comment by maxim-kornienko** [comment]
@yegor256 jcabi/jcabi-github/pull/962 here it is

**Comment by dmarkov** [comment]
once `955-60da9c34` puzzle is resolved, this ticket will be complete

**Comment by dmarkov** [comment]
Finished, thanks, closing..

**Comment by dmarkov** [comment]
@maxim-kornienko Thanks a lot, I just topped your account for **30 mins**, transaction ID `50300798`

+30 to your rating, your total score is +75

**Comment by dmarkov** [comment]
the last puzzle `955-60da9c34`/#987 solved
