### ISSUE TITLE
MkStars.java:45-45: Implement MkStars.starred() operation....

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-github#956]
Puzzle `919-008dea91` in `src/main/java/com/jcabi/github/mock/MkStars.java:45-45` has to be resolved: Implement MkStars.starred() operation.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by dmarkov** [comment]
@apocarteres please pick this up, and keep in mind [these instructions](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions - ask right here

Budget here is **30 mins** (keep [this principle](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind)

**Comment by apocarteres** [comment]
ok. picked up

**Comment by apocarteres** [comment]
done. also added puzzle #957 it's directly related to this issue. I can pick it up

**Comment by apocarteres** [comment]
anyone on check and approve PR https://github.com/jcabi/jcabi-github/pull/958 ?

**Comment by dmarkov** [comment]
@apocarteres the ticket is with you for 13 days already. If it's not finished in the next 2 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle, [this article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck

do not forget that you should remove the `@todo` puzzle from the source code

-30 added to your rating, current score is: [-30](http://www.netbout.com/b/35111?open=rating)

**Comment by yegor256** [comment]
@dmarkov looks like we need more time here

**Comment by dmarkov** [comment]
> @dmarkov looks like we need more time here

@yegor256 of course, thanks for letting me know, take your time

**Comment by dmarkov** [comment]
I'm closing the issue...

**Comment by dmarkov** [comment]
@apocarteres Thank you, I've added **30 mins** to your account in payment/transaction "`50570774`"; +30 added to your rating, current score is: [+60](http://www.netbout.com/b/35111?open=rating)
