### ISSUE TITLE
MkStars.java:46-48: Implement star() and unstar() operations....

### ISSUE THREAD

**Issue by apocarteres** [jcabi/jcabi-github#957]
Implement star() and unstar() methods in MkStars.java and get <code>@Ignore</code> annotation in MkStarsTest.java rid off from methods repoIsStarredIfUserStarredThat() and repoIsNotStarredIfUserUnStarredThat()

**Comment by yegor256** [comment]
you're not supposed to report tasks this way. only bugs.

**Comment by apocarteres** [comment]
ok. sorry for inconvenience.
