### ISSUE TITLE
Implement RtObjectPaginator utility for parsing json object to collection of objects.

### ISSUE THREAD

**Issue by nhekfqn** [jcabi/jcabi-github#960]
There is RtPaginator utility for parsing json array to collection of objects using mapper, need similar utility for json objects.

See comments at https://github.com/jcabi/jcabi-github/issues/954

When utility implemented, use it in RtRepo.languages() instead of manually parse json object fields.

**Comment by yegor256** [comment]
@nhekfqn how exactly do you want it to work? I mean, what should be the output? In case of `RtPaginator` it is a collection of objects. What will be the result in this case?

**Comment by nhekfqn** [comment]
@yegor256 same way as RtPaginator but input is json object (key-value pair actually), output is also collection of objects.

E.g. input

{
    "id1":100,
    "id2":200,
    "id3":450
}

Java bean

public class Supply {

    private final String id;
    private final int amount;

    // constructor and getters

}

RtObjectPaginator usage should be like

RtObjectPaginator<Supply> op = new RtObjectPaginator<>(
    req,
    new RtObjectPaginator.Mapping<String, JsonNumber, Supply>() {
        public Supply map(String key, JsonNumber jsonNumber) {
            return new Supply(key, jsonNumber.intValue());
        }
    }
});

**Comment by nhekfqn** [comment]
@yegor256 According to http://www.yegor256.com/2014/04/12/puzzle-driven-development-by-roles.html do I understand right that I should be paid for tickets like this one? Could you please explain workflow here - I've submitted a ticket, what has to be done next?

**Comment by yegor256** [comment]
@nhekfqn you did everything right, but I still don't understand the idea of this bug/suggestion. First, we don't work with Java beans. how we will "construct" objects? via reflection?

**Comment by yegor256** [comment]
@nhekfqn wait, maybe I miss something... give me a few mins

**Comment by yegor256** [comment]
Here is how you can implement `RtRepo.languages()` in a more compact and functional way, using Guava:

```java
final JsonObject object = ;
return Lists.transform(
  json.fetch().entrySet(),
  new Function<Map.Entry<String, JsonValue>, Language>() {
    @Override
    public JsonValue apply(Map.Entry<String, JsonValue> entry) {
      return new RtLanguage(
        name,
        object.getJsonNumber(name).longValue()
      );
    }
  }
);
```

So, what you're suggesting is already implemented in Guava, just use it.
