### ISSUE TITLE
Incomplete documentation: which scopes should OAuth token have?

### ISSUE THREAD

**Issue by darkled** [jcabi/jcabi-github#963]
README.md says that one needs to create a new Github OAuth access token to execute integration tests, but it is unclear which scopes should be selected in generation process.

**Comment by dmarkov** [comment]
this task will get someone's attention soon

**Comment by dmarkov** [comment]
@maurezen please go ahead, it's your task now, keep [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions you may have; The budget of this task is **30 mins**. This is exactly how much time will be compensated, when the task is completed. Read about our [Definition of Done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by dmarkov** [comment]
@darkled thank you for the ticket reported, I topped your account for 15 mins, transaction `49978575`

**Comment by maurezen** [comment]
@dmarkov the scopes needed are gists, user:email, public_repo and read:public_key, right? Just checking so I didn't miss anything.

**Comment by maurezen** [comment]
@dmarkov, ping. It's been 48 hours since I asked you a question, could you please react somehow?

**Comment by yegor256** [comment]
@maurezen you should ask @darkled, he is the reporter of the ticket, see http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#1.-keep-it-one-on-one

**Comment by darkled** [comment]
@yegor256 if I knew which scopes are needed I wouldn't create this issue. What should we do then?

**Comment by maurezen** [comment]
@yegor256 the reporter is incapable of answering this question. Is research within the scope of this issue?

**Comment by maurezen** [comment]
@yegor256 @darkled never mind, created a pull request here #974

**Comment by maurezen** [comment]
@darkled pull request #974 has been merged into master, please close the ticket. I think you would also find #975 useful.

**Comment by darkled** [comment]
@maurezen thanks!

**Comment by dmarkov** [comment]
@maurezen Thank you, I've added **30 mins** to your account in payment/transaction "`50300828`"; +30 to your rating, your total score is [+495](http://www.netbout.com/b/35102?open=rating)
