### ISSUE TITLE
MkStars.java:46-47: Implement MkStars.star() and MkStars.unstar() operations....

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-github#965]
Puzzle `950-4b919e8a` in `src/main/java/com/jcabi/github/mock/MkStars.java:46-47` has to be resolved: Implement MkStars.star() and MkStars.unstar() operations. Don't forget about unit tests.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by dmarkov** [comment]
@alevohin This task is yours, please go ahead keeping in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If any questions, don't hesitate to ask right here... Budget here is **30 mins** (keep [this principle](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind)

**Comment by alevohin** [comment]
@dmarkov issue https://github.com/jcabi/jcabi-github/issues/956 must be closed before.

**Comment by alevohin** [comment]
@dmarkov release 0.18.7. Please check and close issue.

**Comment by dmarkov** [comment]
@alevohin you're holding this task for 12 days already. as a reminder, don't forget to remove the `@todo` puzzle from the source code. -30 to your rating, your total score is [+150](http://www.netbout.com/b/35105?open=rating)

**Comment by alevohin** [comment]
@dmarkov @yegor256 changes for this issue included at release 0.18.7 2 days ago. What's wrong? Close this issue.

**Comment by dmarkov** [comment]
Done, thanks all, closing..

**Comment by dmarkov** [comment]
@alevohin paid, thanks, added **30 mins** to your account, payment `50570811`; added +30 to your rating, now it is equal to [+270](http://www.netbout.com/b/35105?open=rating)
