### ISSUE TITLE
Github class documentation

### ISSUE THREAD

**Issue by matthew-white** [jcabi/jcabi-github#969]
The [`Github` documentation](https://github.com/jcabi/jcabi-github/blob/4fda54207bd5a8b36ad134d0745ee882880a2beb/src/main/java/com/jcabi/github/Github.java#L48-53) reads:

> This is how you start communicating with Github API:

> ```
 Github github = new RtGithub(oauthKey);
 Repo repo = github.repo("jcabi/jcabi-github");
 Issues issues = repo.issues();
 Issue issue = issues.post("issue title", "issue body");
```

However, the `Github` class doesn't have a `repo()` method, right?

**Comment by yegor256** [comment]
yes, it's a typo. You should call `github.repos().repo(..)`. feel free to submit a pull request for the fix

**Comment by dmarkov** [comment]
@yegor256 only @matthew-white can close this issue, since he opened it
