### ISSUE TITLE
Copyright section is outdated

### ISSUE THREAD

**Issue by maurezen** [jcabi/jcabi-github#970]
Copyright sections still feature 2014 as a year.

**Comment by dmarkov** [comment]
I'm aware of the task, give me some time to find a developer...

**Comment by dmarkov** [comment]
@oruam85 please help, the task is yours

**Comment by dmarkov** [comment]
@maurezen many thanks for the bug report, I added 15 mins to your acc, transaction `50519477`

**Comment by oruam85** [comment]
@maurezen @dmarkov the PR is https://github.com/jcabi/jcabi-github/pull/998

**Comment by oruam85** [comment]
@maurezen the PR was merged. Please close this bug.

**Comment by dmarkov** [comment]
@oruam85 Much obliged! I've added **30 mins** to your account in payment "50842279"... added +30 to your rating, now it is equal to +150
