### ISSUE TITLE
Stars API must be refactored or moved to Github

### ISSUE THREAD

**Issue by alevohin** [jcabi/jcabi-github#972]
Stars API now is part of Repo API - it is wrong. Methods of Stars API is also have parameters of user/repo name - they are redundant. It's better to do one of this:
1) Refactor Stars API. Methods starred, star and unstar is for logged in user only. All parameters show be removed from methods. Need new method Repo repo(). Repo must provide username and reponame for methods starred/star/unstar.
2) Move Stars from Repo to Github.

**Comment by dmarkov** [comment]
this task will get someone's attention soon

**Comment by dmarkov** [comment]
@pinaf please pick this up, and keep in mind [these instructions](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions - ask right here; This task's budget is **30 mins**. This is exactly how much will be paid when the problem explained above is solved. See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by pinaf** [comment]
@dmarkov please pull from [PR 981](https://github.com/jcabi/jcabi-github/pull/981)

**Comment by pinaf** [comment]
something I believe is worth mentioning. Running **mvn clean install -Pqulice** on this project takes waaay too long...

> [INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 09:00 min
[INFO] Finished at: 2015-01-12T22:30:22-03:00
[INFO] Final Memory: 50M/410M
[INFO] ------------------------------------------------------------------------

**Comment by pinaf** [comment]
@alevohin @dmarkov merged. please close.

**Comment by alevohin** [comment]
@alevohin thanks!

**Comment by pinaf** [comment]
@dmarkov this was closed 2 days ago. does this make my average speed slower?

**Comment by yegor256** [comment]
@pinaf lower than what? :)

**Comment by pinaf** [comment]
@yegor256 well do you measure the time to complete the task until the issue is closed or until @dmarkov notices that the issue is closed?

**Comment by yegor256** [comment]
@pinaf it's the time between the moment you are assigned to the task and the moment you're paid

**Comment by dmarkov** [comment]
@pinaf Much obliged! I've added **30 mins** to your account in payment "AP-5T852175BW507970C". +30 added to your rating, at the moment it is: [+60](http://www.netbout.com/b/35128?open=rating)

**Comment by yegor256** [comment]
@dmarkov please add extra 15 mins to @alevohin

**Comment by dmarkov** [comment]
> @dmarkov please add extra 15 mins to @alevohin 

@yegor256 I've paid 15 mins to @alevohin in transaction `50614484`

**Comment by yegor256** [comment]
@rultor release, tag is `0.18.9`
