### ISSUE TITLE
Incorrect documentation - example integration test run script

### ISSUE THREAD

**Issue by maurezen** [jcabi/jcabi-github#976]
In README.md in the example of running integration tests with the oauth token the test case RtGistITCase is used. However, the test requires two oauth tokens, supplied via properties failsafe.github.key and failsafe.github.key.second, whereas the example only supplies one.

**Comment by dmarkov** [comment]
this task will get someone's attention soon

**Comment by dmarkov** [comment]
@maurezen many thanks for the report, I topped your account for 15 mins, transaction 50342885

**Comment by dmarkov** [comment]
@nhekfqn please go ahead, it's your task now, keep [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions you may have; The budget of this task is **30 mins**. This is exactly how much time will be compensated, when the task is completed. Read about our [Definition of Done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by nhekfqn** [comment]
@dmarkov Submitted https://github.com/jcabi/jcabi-github/issues/993 please provide info requested.

**Comment by nhekfqn** [comment]
@dmarkov submitted PR https://github.com/jcabi/jcabi-github/pull/1001

**Comment by nhekfqn** [comment]
@dmarkov related pull request has been merged.

**Comment by nhekfqn** [comment]
@dmarkov ticket closed, can I get paid please?

**Comment by dmarkov** [comment]
@nhekfqn **30 mins** sent to your balance (ID `50904331`), many thanks!... +30 to your rating, your total score is [+75](http://www.netbout.com/b/35123?open=rating)
