### ISSUE TITLE
Strange maven configuration

### ISSUE THREAD

**Issue by maurezen** [jcabi/jcabi-github#977]
In pom.xml maven-failsafe-plugin is configured in two separate places - in pluginManagement/plugins section of build and in plugins section of build. Wouldn't it be more clear and streamlined to merge the configuration to one section?

**Comment by yegor256** [comment]
@maurezen definitely a bug, thanks

**Comment by dmarkov** [comment]
I'll find a developer for the task soon...

**Comment by dmarkov** [comment]
@maxim-kornienko this task is yours, please help (see our key [principles of work](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html)). If you have any technical questions, don't hesitate to ask right here. The budget of this task is **30 mins**. This is exactly how much time will be compensated, when the task is completed. Read about our [Definition of Done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by maxim-kornienko** [comment]
Done in jcabi/jcabi-github/pull/992

**Comment by dmarkov** [comment]
@maurezen thanks for the ticket, your account was topped for 15 mins, payment 50517818

**Comment by maxim-kornienko** [comment]
@maurezen Let's close the ticket as pull request #992 is merged

**Comment by dmarkov** [comment]
@maxim-kornienko Much appreciated! **30 mins** was added to your account, payment ID `52066203`; +30 added to your rating, at the moment it is: +165
