### ISSUE TITLE
Broken link at http://github.jcabi.com

### ISSUE THREAD

**Issue by dpisarenko** [jcabi/jcabi-github#984]
The link titled *Javadoc* at http://github.jcabi.com leads to a missing page http://github.jcabi.com/apidocs-0.18.6/com/jcabi/github/index.html .

Please change the link so that it points to an existing page.

**Comment by dmarkov** [comment]
we'll find someone to do this task, soon

**Comment by dmarkov** [comment]
@marczeeee please go ahead, it's your task now, keep [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions you may have. This task's budget is **30 mins**. This is exactly how much will be paid when the problem explained above is solved. See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by Marczeeee** [comment]
@dpisarenko Fix is merged with PR #988, the issue can be closed.

**Comment by dmarkov** [comment]
@marczeeee Thanks so much! Your account was topped up for **30 mins** (transaction ID is `50573513`); +30 added to your rating, at the moment it is: +60
