### ISSUE TITLE
RtRepo.java:53-54: Uncomment test RtRepoTest.iteratesLanguages() when RtRepoITCase.languages()...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-github#987]
Puzzle `955-60da9c34` in `src/main/java/com/jcabi/github/RtRepo.java:53-54` has to be resolved: Uncomment test RtRepoTest.iteratesLanguages() when RtRepoITCase.languages() implemented.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by dmarkov** [comment]
@maxim-kornienko this ticket is yours now, please proceed, and keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions you should ask right here... Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by maxim-kornienko** [comment]
Done in jcabi/jcabi-github/pull/991

**Comment by dmarkov** [comment]
The task is done, thanks all, I'm closing it

**Comment by dmarkov** [comment]
@maxim-kornienko Thanks a lot, I just topped your account for **30 mins**, transaction ID `50616711`. +30 added to your rating, current score is: +135
