### ISSUE TITLE
#976 unclear what OAuth tokens are used

### ISSUE THREAD

**Issue by nhekfqn** [jcabi/jcabi-github#993]
I'm trying to fix https://github.com/jcabi/jcabi-github/issues/976 but it's unclear what two OAuth tokens should be used for.

There is one test in RtGistITCase case using 'failsafe.github.key.second' property that should be documented.

```
@Test
    public void forksGist() throws Exception {
        final String filename = "filename1.txt";
        final String content = "content of file1";
        final Gists gists1 = RtGistITCase.github("failsafe.github.key").gists();
        final Gists gists2 = RtGistITCase.github("failsafe.github.key.second")
            .gists();
        final Gist gist = gists1.get(
            gists2.create(Collections.singletonMap(filename, content), false)
                .identifier()
        );
        final Gist forked = gist.fork();
        try {
            MatcherAssert.assertThat(
                forked.read(filename),
                Matchers.equalTo(content)
            );
        } finally {
            gists1.remove(forked.identifier());
            gists2.remove(gist.identifier());
        }
    }
```

To document the test usage I need to understand what the properties is used for:
Is the second token of separate Github account?
If so, what permissions second token need?

**Comment by yegor256** [comment]
@nhekfqn it's just a second Github account. I'm not sure what permissions are mandatory there, it's for you to find out, I guest, in the scope of #976.
